<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>disable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Company>YuyuyuiPrivateServer</Company>
        <Product>GoalKeeper</Product>
        <VersionPrefix>0.1.0</VersionPrefix>
        <AssemblyVersion>$(Version)</AssemblyVersion>
        <FileVersion>$(Version)</FileVersion>
        <DebugType>embedded</DebugType>
        <TargetFramework>net6.0</TargetFramework>
        <LangVersion>latest</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Yuyuyui.GoalKeeper.Native" Version="1.0.6" />
    </ItemGroup>

</Project>
