//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yuyuyui.PrivateServer.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_zh {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_zh() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Yuyuyui.PrivateServer.Localization.Resources.zh", typeof(Resources_zh).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始
        ///账号
        ///转移.
        /// </summary>
        internal static string AT_BUTTON_START {
            get {
                return ResourceManager.GetString("AT_BUTTON_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 停止
        ///账号
        ///转移.
        /// </summary>
        internal static string AT_BUTTON_STOP {
            get {
                return ResourceManager.GetString("AT_BUTTON_STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注意：.
        /// </summary>
        internal static string AT_NOTE {
            get {
                return ResourceManager.GetString("AT_NOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更多帮助信息请参考帮助页面。.
        /// </summary>
        internal static string AT_NOTE_MORE_INFO {
            get {
                return ResourceManager.GetString("AT_NOTE_MORE_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 一次仅可转移一个账户。.
        /// </summary>
        internal static string AT_NOTE_ONE_ACCOUNT {
            get {
                return ResourceManager.GetString("AT_NOTE_ONE_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 转移完成后，必须完全重新启动游戏。.
        /// </summary>
        internal static string AT_NOTE_RESTART {
            get {
                return ResourceManager.GetString("AT_NOTE_RESTART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 精灵.
        /// </summary>
        internal static string AT_TASK_ACCESSORIES {
            get {
                return ResourceManager.GetString("AT_TASK_ACCESSORIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 卡牌.
        /// </summary>
        internal static string AT_TASK_CARDS {
            get {
                return ResourceManager.GetString("AT_TASK_CARDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 角色亲密度.
        /// </summary>
        internal static string AT_TASK_CHARACTER_FAMILIARITIES {
            get {
                return ResourceManager.GetString("AT_TASK_CHARACTER_FAMILIARITIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 队伍.
        /// </summary>
        internal static string AT_TASK_DECKS {
            get {
                return ResourceManager.GetString("AT_TASK_DECKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 账号信息.
        /// </summary>
        internal static string AT_TASK_HEADER {
            get {
                return ResourceManager.GetString("AT_TASK_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 账号身份.
        /// </summary>
        internal static string AT_TASK_ID {
            get {
                return ResourceManager.GetString("AT_TASK_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 强化道具.
        /// </summary>
        internal static string AT_TASK_ITEMS_ENHANCEMENT {
            get {
                return ResourceManager.GetString("AT_TASK_ITEMS_ENHANCEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 活动道具.
        /// </summary>
        internal static string AT_TASK_ITEMS_EVENT {
            get {
                return ResourceManager.GetString("AT_TASK_ITEMS_EVENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 神花解放道具.
        /// </summary>
        internal static string AT_TASK_ITEMS_EVOLUTION {
            get {
                return ResourceManager.GetString("AT_TASK_ITEMS_EVOLUTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 体力道具.
        /// </summary>
        internal static string AT_TASK_ITEMS_STAMINA {
            get {
                return ResourceManager.GetString("AT_TASK_ITEMS_STAMINA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 称号.
        /// </summary>
        internal static string AT_TASK_ITEMS_TITLE {
            get {
                return ResourceManager.GetString("AT_TASK_ITEMS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 玩家信息.
        /// </summary>
        internal static string AT_TASK_PROFILE {
            get {
                return ResourceManager.GetString("AT_TASK_PROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zh.
        /// </summary>
        internal static string LAN_CODE {
            get {
                return ResourceManager.GetString("LAN_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始账号转移！.
        /// </summary>
        internal static string LOG_AT_START {
            get {
                return ResourceManager.GetString("LOG_AT_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 停止账号转移！.
        /// </summary>
        internal static string LOG_AT_STOP {
            get {
                return ResourceManager.GetString("LOG_AT_STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}转移成功.
        /// </summary>
        internal static string LOG_AT_TRANSFER_SUCCESS {
            get {
                return ResourceManager.GetString("LOG_AT_TRANSFER_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 初始化用户界面.
        /// </summary>
        internal static string LOG_GUI_INITIALIZED {
            get {
                return ResourceManager.GetString("LOG_GUI_INITIALIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 私服已启动！.
        /// </summary>
        internal static string LOG_PS_START {
            get {
                return ResourceManager.GetString("LOG_PS_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 私服已停止！.
        /// </summary>
        internal static string LOG_PS_STOP {
            get {
                return ResourceManager.GetString("LOG_PS_STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关于.
        /// </summary>
        internal static string NAV_BUTTON_ABOUT {
            get {
                return ResourceManager.GetString("NAV_BUTTON_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 帮助.
        /// </summary>
        internal static string NAV_BUTTON_HELP {
            get {
                return ResourceManager.GetString("NAV_BUTTON_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日志.
        /// </summary>
        internal static string NAV_BUTTON_LOG {
            get {
                return ResourceManager.GetString("NAV_BUTTON_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置.
        /// </summary>
        internal static string NAV_BUTTON_SETTINGS {
            get {
                return ResourceManager.GetString("NAV_BUTTON_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 运行状态.
        /// </summary>
        internal static string NAV_BUTTON_STATUS {
            get {
                return ResourceManager.GetString("NAV_BUTTON_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 账号转移.
        /// </summary>
        internal static string NAV_BUTTON_TRANSFER {
            get {
                return ResourceManager.GetString("NAV_BUTTON_TRANSFER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 《结城友奈是勇者 闪光的花结》私服.
        /// </summary>
        internal static string PROJ_DESC {
            get {
                return ResourceManager.GetString("PROJ_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启动.
        /// </summary>
        internal static string PS_BUTTON_START {
            get {
                return ResourceManager.GetString("PS_BUTTON_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启动私服.
        /// </summary>
        internal static string PS_BUTTON_START_DESC {
            get {
                return ResourceManager.GetString("PS_BUTTON_START_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 停止.
        /// </summary>
        internal static string PS_BUTTON_STOP {
            get {
                return ResourceManager.GetString("PS_BUTTON_STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 停止私服.
        /// </summary>
        internal static string PS_BUTTON_STOP_DESC {
            get {
                return ResourceManager.GetString("PS_BUTTON_STOP_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 转移中.
        /// </summary>
        internal static string PS_BUTTON_TRANSFER {
            get {
                return ResourceManager.GetString("PS_BUTTON_TRANSFER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在转移账号…….
        /// </summary>
        internal static string PS_BUTTON_TRANSFER_DESC {
            get {
                return ResourceManager.GetString("PS_BUTTON_TRANSFER_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新中.
        /// </summary>
        internal static string PS_BUTTON_UPDATE {
            get {
                return ResourceManager.GetString("PS_BUTTON_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在更新所需文件…….
        /// </summary>
        internal static string PS_BUTTON_UPDATE_DESC {
            get {
                return ResourceManager.GetString("PS_BUTTON_UPDATE_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 如何使用账号转移.
        /// </summary>
        internal static string PS_HELP_AT {
            get {
                return ResourceManager.GetString("PS_HELP_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 返回.
        /// </summary>
        internal static string PS_HELP_BACK_BUTTON {
            get {
                return ResourceManager.GetString("PS_HELP_BACK_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 如何安装SSL证书（Android设备）.
        /// </summary>
        internal static string PS_HELP_CERT_ANDROID {
            get {
                return ResourceManager.GetString("PS_HELP_CERT_ANDROID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 如何安装SSL证书（iOS设备）.
        /// </summary>
        internal static string PS_HELP_CERT_IOS {
            get {
                return ResourceManager.GetString("PS_HELP_CERT_IOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 这个项目是什么.
        /// </summary>
        internal static string PS_HELP_INTRO {
            get {
                return ResourceManager.GetString("PS_HELP_INTRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 如何连接至代理服务器.
        /// </summary>
        internal static string PS_HELP_PROXY {
            get {
                return ResourceManager.GetString("PS_HELP_PROXY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 如何使用私服.
        /// </summary>
        internal static string PS_HELP_PS {
            get {
                return ResourceManager.GetString("PS_HELP_PS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 我该使用哪个？.
        /// </summary>
        internal static string PS_STATUS_CHOOSE_IP {
            get {
                return ResourceManager.GetString("PS_STATUS_CHOOSE_IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请使用以下之一作为代理服务器地址：.
        /// </summary>
        internal static string PS_STATUS_CHOOSE_MULTIPLE {
            get {
                return ResourceManager.GetString("PS_STATUS_CHOOSE_MULTIPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 没有可以作为代理服务器的地址！.
        /// </summary>
        internal static string PS_STATUS_CHOOSE_NONE {
            get {
                return ResourceManager.GetString("PS_STATUS_CHOOSE_NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请使用以下地址作为代理服务器地址：.
        /// </summary>
        internal static string PS_STATUS_CHOOSE_SINGLE {
            get {
                return ResourceManager.GetString("PS_STATUS_CHOOSE_SINGLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消过滤.
        /// </summary>
        internal static string PS_STATUS_CLEAR_FILTER_BUTTON {
            get {
                return ResourceManager.GetString("PS_STATUS_CLEAR_FILTER_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 过滤.
        /// </summary>
        internal static string PS_STATUS_FILTER_IP_BUTTON {
            get {
                return ResourceManager.GetString("PS_STATUS_FILTER_IP_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 代理服务器正在监听端口.
        /// </summary>
        internal static string PS_STATUS_PORT_LISTEN {
            get {
                return ResourceManager.GetString("PS_STATUS_PORT_LISTEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 私服正在运行。.
        /// </summary>
        internal static string PS_STATUS_STARTED {
            get {
                return ResourceManager.GetString("PS_STATUS_STARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 私服已停止。.
        /// </summary>
        internal static string PS_STATUS_STOPPED {
            get {
                return ResourceManager.GetString("PS_STATUS_STOPPED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP地址.
        /// </summary>
        internal static string PS_STATUS_TEXT_IP_ADDRESS {
            get {
                return ResourceManager.GetString("PS_STATUS_TEXT_IP_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 子网掩码.
        /// </summary>
        internal static string PS_STATUS_TEXT_SUBNET_MASK {
            get {
                return ResourceManager.GetString("PS_STATUS_TEXT_SUBNET_MASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在转移账号。.
        /// </summary>
        internal static string PS_STATUS_TRANSFERRING {
            get {
                return ResourceManager.GetString("PS_STATUS_TRANSFERRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在更新所需文件…….
        /// </summary>
        internal static string PS_STATUS_UPDATING {
            get {
                return ResourceManager.GetString("PS_STATUS_UPDATING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 花结私服.
        /// </summary>
        internal static string WINDOW_TITLE {
            get {
                return ResourceManager.GetString("WINDOW_TITLE", resourceCulture);
            }
        }
    }
}
