//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yuyuyui.PrivateServer.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_zh {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_zh() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Yuyuyui.PrivateServer.Localization.Resources.zh", typeof(Resources_zh).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新日志.
        /// </summary>
        internal static string HTML_RELEASE_NOTES_TITLE {
            get {
                return ResourceManager.GetString("HTML_RELEASE_NOTES_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zh.
        /// </summary>
        internal static string LAN_CODE {
            get {
                return ResourceManager.GetString("LAN_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 跟随系统.
        /// </summary>
        internal static string LAN_DEFAULT {
            get {
                return ResourceManager.GetString("LAN_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 初始化用户界面.
        /// </summary>
        internal static string LOG_GUI_INITIALIZED {
            get {
                return ResourceManager.GetString("LOG_GUI_INITIALIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LibGK Lambda调用失败！.
        /// </summary>
        internal static string LOG_LIBGK_LAMBDA_FAILED {
            get {
                return ResourceManager.GetString("LOG_LIBGK_LAMBDA_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在监听.
        /// </summary>
        internal static string LOG_LISTENING_AT {
            get {
                return ResourceManager.GetString("LOG_LISTENING_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已向玩家分发默认精灵.
        /// </summary>
        internal static string LOG_PS_ACCESSORY_ASSIGN_DEFAULT {
            get {
                return ResourceManager.GetString("LOG_PS_ACCESSORY_ASSIGN_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获得新精灵，master_id = {0}.
        /// </summary>
        internal static string LOG_PS_ACCESSORY_ASSIGN_NEW {
            get {
                return ResourceManager.GetString("LOG_PS_ACCESSORY_ASSIGN_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 玩家精灵{0}等级为{1}.
        /// </summary>
        internal static string LOG_PS_ACCESSORY_ENHANCEMENT_LEVEL {
            get {
                return ResourceManager.GetString("LOG_PS_ACCESSORY_ENHANCEMENT_LEVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 玩家精灵{0}数量减少{1}.
        /// </summary>
        internal static string LOG_PS_ACCESSORY_QUANTITY_DECREASED {
            get {
                return ResourceManager.GetString("LOG_PS_ACCESSORY_QUANTITY_DECREASED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 玩家精灵{0}数量增加{1}.
        /// </summary>
        internal static string LOG_PS_ACCESSORY_QUANTITY_INCREASED {
            get {
                return ResourceManager.GetString("LOG_PS_ACCESSORY_QUANTITY_INCREASED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已禁用账号{0}.
        /// </summary>
        internal static string LOG_PS_ACCOUNT_BANNED {
            get {
                return ResourceManager.GetString("LOG_PS_ACCOUNT_BANNED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在禁用账号{0}.
        /// </summary>
        internal static string LOG_PS_ACCOUNT_BANNING {
            get {
                return ResourceManager.GetString("LOG_PS_ACCOUNT_BANNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;API错误&gt; .
        /// </summary>
        internal static string LOG_PS_API_ERROR_TEMPLATE {
            get {
                return ResourceManager.GetString("LOG_PS_API_ERROR_TEMPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未实现的API：.
        /// </summary>
        internal static string LOG_PS_API_NOT_IMPLEMENTED {
            get {
                return ResourceManager.GetString("LOG_PS_API_NOT_IMPLEMENTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 玩家{0}勇者勋章+{1}.
        /// </summary>
        internal static string LOG_PS_BRAVE_COIN_INCREASE {
            get {
                return ResourceManager.GetString("LOG_PS_BRAVE_COIN_INCREASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已向玩家分发默认卡牌.
        /// </summary>
        internal static string LOG_PS_CARD_ASSIGN_DEFAULT {
            get {
                return ResourceManager.GetString("LOG_PS_CARD_ASSIGN_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 获得新卡牌，master_id = {0}.
        /// </summary>
        internal static string LOG_PS_CARD_ASSIGN_NEW {
            get {
                return ResourceManager.GetString("LOG_PS_CARD_ASSIGN_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 必杀技升级.
        /// </summary>
        internal static string LOG_PS_CARD_ENHANCEMENT_ACTIVE_SKILL_LEVEL_UP {
            get {
                return ResourceManager.GetString("LOG_PS_CARD_ENHANCEMENT_ACTIVE_SKILL_LEVEL_UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 必杀技升级概率为{0}%.
        /// </summary>
        internal static string LOG_PS_CARD_ENHANCEMENT_ACTIVE_SKILL_LEVEL_UP_PROBABILITY {
            get {
                return ResourceManager.GetString("LOG_PS_CARD_ENHANCEMENT_ACTIVE_SKILL_LEVEL_UP_PROBABILITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 亲密度{0}协作等级增加{1}.
        /// </summary>
        internal static string LOG_PS_CARD_ENHANCEMENT_AFFINITY_ASSIST_LEVEL_INCREASE {
            get {
                return ResourceManager.GetString("LOG_PS_CARD_ENHANCEMENT_AFFINITY_ASSIST_LEVEL_INCREASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 亲密度{0}增加{1}.
        /// </summary>
        internal static string LOG_PS_CARD_ENHANCEMENT_AFFINITY_INCREASE {
            get {
                return ResourceManager.GetString("LOG_PS_CARD_ENHANCEMENT_AFFINITY_INCREASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成功触发料理大成功.
        /// </summary>
        internal static string LOG_PS_CARD_ENHANCEMENT_BIG_HIT {
            get {
                return ResourceManager.GetString("LOG_PS_CARD_ENHANCEMENT_BIG_HIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 被动技能升级.
        /// </summary>
        internal static string LOG_PS_CARD_ENHANCEMENT_SUPPORT_SKILL_LEVEL_UP {
            get {
                return ResourceManager.GetString("LOG_PS_CARD_ENHANCEMENT_SUPPORT_SKILL_LEVEL_UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 被动技能升级概率为{0}%.
        /// </summary>
        internal static string LOG_PS_CARD_ENHANCEMENT_SUPPORT_SKILL_LEVEL_UP_PROBABILITY {
            get {
                return ResourceManager.GetString("LOG_PS_CARD_ENHANCEMENT_SUPPORT_SKILL_LEVEL_UP_PROBABILITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 料理角色{0} -&gt; 目标角色{1}.
        /// </summary>
        internal static string LOG_PS_CARD_ENHANCMENT_COOKING_CHARACTER {
            get {
                return ResourceManager.GetString("LOG_PS_CARD_ENHANCMENT_COOKING_CHARACTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 玩家卡牌{0}神花解放等级由{1}变为{2}.
        /// </summary>
        internal static string LOG_PS_CARD_EVOLUTION_LEVEL_CHANGE {
            get {
                return ResourceManager.GetString("LOG_PS_CARD_EVOLUTION_LEVEL_CHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 玩家卡牌{0}主ID由{1}变为{2}.
        /// </summary>
        internal static string LOG_PS_CARD_EVOLUTION_MASTER_ID_CHANGE {
            get {
                return ResourceManager.GetString("LOG_PS_CARD_EVOLUTION_MASTER_ID_CHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 玩家{0}已创建会话，会话ID：{1}，会话密钥：{2}.
        /// </summary>
        internal static string LOG_PS_CREATE_SESSION {
            get {
                return ResourceManager.GetString("LOG_PS_CREATE_SESSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已为玩家设置默认队伍.
        /// </summary>
        internal static string LOG_PS_DECK_SET_DEFAULT {
            get {
                return ResourceManager.GetString("LOG_PS_DECK_SET_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 若要在任何时刻退出程序，请按回车键。.
        /// </summary>
        internal static string LOG_PS_ENTER_TO_EXIT {
            get {
                return ResourceManager.GetString("LOG_PS_ENTER_TO_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 玩家{0}将玩家{1}从好友列表中删除.
        /// </summary>
        internal static string LOG_PS_FRIEND_DELETED {
            get {
                return ResourceManager.GetString("LOG_PS_FRIEND_DELETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 玩家{0}和{1}已成为好友！.
        /// </summary>
        internal static string LOG_PS_FRIEND_REQUEST_ACCEPTED {
            get {
                return ResourceManager.GetString("LOG_PS_FRIEND_REQUEST_ACCEPTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已创建好友申请{0} ({1}=&gt;{2}).
        /// </summary>
        internal static string LOG_PS_FRIEND_REQUEST_CREATED {
            get {
                return ResourceManager.GetString("LOG_PS_FRIEND_REQUEST_CREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已删除好友申请{0} ({1}=&gt;{2})！.
        /// </summary>
        internal static string LOG_PS_FRIEND_REQUEST_DELETED {
            get {
                return ResourceManager.GetString("LOG_PS_FRIEND_REQUEST_DELETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发现已存在的好友申请{0} ({1}=&gt;{2}).
        /// </summary>
        internal static string LOG_PS_FRIEND_REQUEST_FOUND {
            get {
                return ResourceManager.GetString("LOG_PS_FRIEND_REQUEST_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已找到对称的好友申请{0}（{1}=&gt;{2}）并已自动接受.
        /// </summary>
        internal static string LOG_PS_FRIEND_REQUEST_FOUND_SYMMETRIC {
            get {
                return ResourceManager.GetString("LOG_PS_FRIEND_REQUEST_FOUND_SYMMETRIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 玩家{0}拒绝了来自玩家{1}的好友申请.
        /// </summary>
        internal static string LOG_PS_FRIEND_REQUEST_REJECTED {
            get {
                return ResourceManager.GetString("LOG_PS_FRIEND_REQUEST_REJECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 玩家{1}移除了好友申请{0}.
        /// </summary>
        internal static string LOG_PS_FRIEND_REQUEST_REMOVED {
            get {
                return ResourceManager.GetString("LOG_PS_FRIEND_REQUEST_REMOVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已向玩家{1}发送好友申请{0}.
        /// </summary>
        internal static string LOG_PS_FRIEND_REQUEST_SENT {
            get {
                return ResourceManager.GetString("LOG_PS_FRIEND_REQUEST_SENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未知状态，不应到达此处！.
        /// </summary>
        internal static string LOG_PS_FRIEND_REQUEST_UNKNOWN {
            get {
                return ResourceManager.GetString("LOG_PS_FRIEND_REQUEST_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UUID为{0}的玩家已连接.
        /// </summary>
        internal static string LOG_PS_GOT_CONNECTION {
            get {
                return ResourceManager.GetString("LOG_PS_GOT_CONNECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 玩家道具{0}数量减少{1}.
        /// </summary>
        internal static string LOG_PS_ITEM_QUANTITY_DECREASED {
            get {
                return ResourceManager.GetString("LOG_PS_ITEM_QUANTITY_DECREASED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在下载{0}…….
        /// </summary>
        internal static string LOG_PS_LOCAL_DATA_DOWNLOADING {
            get {
                return ResourceManager.GetString("LOG_PS_LOCAL_DATA_DOWNLOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 所有资源均为最新.
        /// </summary>
        internal static string LOG_PS_LOCAL_DATA_UP_TO_DATE {
            get {
                return ResourceManager.GetString("LOG_PS_LOCAL_DATA_UP_TO_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已更新{0}个文件.
        /// </summary>
        internal static string LOG_PS_LOCAL_DATA_UPDATED {
            get {
                return ResourceManager.GetString("LOG_PS_LOCAL_DATA_UPDATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在更新所需本地资源…….
        /// </summary>
        internal static string LOG_PS_LOCAL_DATA_UPDATING {
            get {
                return ResourceManager.GetString("LOG_PS_LOCAL_DATA_UPDATING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 玩家{0}硬币数量减少{1}.
        /// </summary>
        internal static string LOG_PS_MONEY_DECREASED {
            get {
                return ResourceManager.GetString("LOG_PS_MONEY_DECREASED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已更新玩家资料：昵称：{0}，签名：{1}.
        /// </summary>
        internal static string LOG_PS_PROFILE_UPDATED {
            get {
                return ResourceManager.GetString("LOG_PS_PROFILE_UPDATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重定向至非官方公开API服务器.
        /// </summary>
        internal static string LOG_PS_REDIRECT_API {
            get {
                return ResourceManager.GetString("LOG_PS_REDIRECT_API", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新玩家{0}已注册.
        /// </summary>
        internal static string LOG_PS_REGISTER_NEW_PLAYER {
            get {
                return ResourceManager.GetString("LOG_PS_REGISTER_NEW_PLAYER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 剧情语言为{0}.
        /// </summary>
        internal static string LOG_PS_SCENARIO_LANGUAGE {
            get {
                return ResourceManager.GetString("LOG_PS_SCENARIO_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 私服已启动！.
        /// </summary>
        internal static string LOG_PS_START {
            get {
                return ResourceManager.GetString("LOG_PS_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 私服已停止！.
        /// </summary>
        internal static string LOG_PS_STOP {
            get {
                return ResourceManager.GetString("LOG_PS_STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在检查{0}分支上的更新…….
        /// </summary>
        internal static string LOG_UPDATE_CHECKING {
            get {
                return ResourceManager.GetString("LOG_UPDATE_CHECKING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已将更新文件下载至{0}.
        /// </summary>
        internal static string LOG_UPDATE_DOWNLOADED {
            get {
                return ResourceManager.GetString("LOG_UPDATE_DOWNLOADED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发现更新：位于{1}分支上的提交{0}。请前往{2}页面下载更新。.
        /// </summary>
        internal static string LOG_UPDATE_FOUND {
            get {
                return ResourceManager.GetString("LOG_UPDATE_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 没有发现更新。.
        /// </summary>
        internal static string LOG_UPDATE_NOT_FOUND {
            get {
                return ResourceManager.GetString("LOG_UPDATE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用旧版本将无法启动私服。.
        /// </summary>
        internal static string LOG_UPDATE_RESTRICTION {
            get {
                return ResourceManager.GetString("LOG_UPDATE_RESTRICTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前版本：{0}.
        /// </summary>
        internal static string LOG_VERSION {
            get {
                return ResourceManager.GetString("LOG_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关于.
        /// </summary>
        internal static string NAV_BUTTON_ABOUT {
            get {
                return ResourceManager.GetString("NAV_BUTTON_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 帮助.
        /// </summary>
        internal static string NAV_BUTTON_HELP {
            get {
                return ResourceManager.GetString("NAV_BUTTON_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日志.
        /// </summary>
        internal static string NAV_BUTTON_LOG {
            get {
                return ResourceManager.GetString("NAV_BUTTON_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新日志.
        /// </summary>
        internal static string NAV_BUTTON_RELEASE {
            get {
                return ResourceManager.GetString("NAV_BUTTON_RELEASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置.
        /// </summary>
        internal static string NAV_BUTTON_SETTINGS {
            get {
                return ResourceManager.GetString("NAV_BUTTON_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 运行状态.
        /// </summary>
        internal static string NAV_BUTTON_STATUS {
            get {
                return ResourceManager.GetString("NAV_BUTTON_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 《结城友奈是勇者 闪光的花结》私服.
        /// </summary>
        internal static string PROJ_DESC_JINCHOGE {
            get {
                return ResourceManager.GetString("PROJ_DESC_JINCHOGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启动.
        /// </summary>
        internal static string PS_BUTTON_START {
            get {
                return ResourceManager.GetString("PS_BUTTON_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启动私服.
        /// </summary>
        internal static string PS_BUTTON_START_DESC {
            get {
                return ResourceManager.GetString("PS_BUTTON_START_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 停止.
        /// </summary>
        internal static string PS_BUTTON_STOP {
            get {
                return ResourceManager.GetString("PS_BUTTON_STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 停止私服.
        /// </summary>
        internal static string PS_BUTTON_STOP_DESC {
            get {
                return ResourceManager.GetString("PS_BUTTON_STOP_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新中.
        /// </summary>
        internal static string PS_BUTTON_UPDATE {
            get {
                return ResourceManager.GetString("PS_BUTTON_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在更新所需文件…….
        /// </summary>
        internal static string PS_BUTTON_UPDATE_DESC {
            get {
                return ResourceManager.GetString("PS_BUTTON_UPDATE_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 返回.
        /// </summary>
        internal static string PS_HELP_BACK_BUTTON {
            get {
                return ResourceManager.GetString("PS_HELP_BACK_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 如何安装SSL证书（Android设备）.
        /// </summary>
        internal static string PS_HELP_CERT_ANDROID {
            get {
                return ResourceManager.GetString("PS_HELP_CERT_ANDROID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 如何安装SSL证书（iOS设备）.
        /// </summary>
        internal static string PS_HELP_CERT_IOS {
            get {
                return ResourceManager.GetString("PS_HELP_CERT_IOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 这个项目是什么.
        /// </summary>
        internal static string PS_HELP_INTRO {
            get {
                return ResourceManager.GetString("PS_HELP_INTRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 如何连接至代理服务器.
        /// </summary>
        internal static string PS_HELP_PROXY {
            get {
                return ResourceManager.GetString("PS_HELP_PROXY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 如何使用Jinchōge（私服）.
        /// </summary>
        internal static string PS_HELP_PS {
            get {
                return ResourceManager.GetString("PS_HELP_PS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 玩家已同意用户协议版本{0}.
        /// </summary>
        internal static string PS_LOG_REGULATION_AGREED {
            get {
                return ResourceManager.GetString("PS_LOG_REGULATION_AGREED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 我该使用哪个？.
        /// </summary>
        internal static string PS_STATUS_CHOOSE_IP {
            get {
                return ResourceManager.GetString("PS_STATUS_CHOOSE_IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请使用以下之一作为代理服务器地址：.
        /// </summary>
        internal static string PS_STATUS_CHOOSE_MULTIPLE {
            get {
                return ResourceManager.GetString("PS_STATUS_CHOOSE_MULTIPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 没有可以作为代理服务器的地址！.
        /// </summary>
        internal static string PS_STATUS_CHOOSE_NONE {
            get {
                return ResourceManager.GetString("PS_STATUS_CHOOSE_NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请使用以下地址作为代理服务器地址：.
        /// </summary>
        internal static string PS_STATUS_CHOOSE_SINGLE {
            get {
                return ResourceManager.GetString("PS_STATUS_CHOOSE_SINGLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消过滤.
        /// </summary>
        internal static string PS_STATUS_CLEAR_FILTER_BUTTON {
            get {
                return ResourceManager.GetString("PS_STATUS_CLEAR_FILTER_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 过滤.
        /// </summary>
        internal static string PS_STATUS_FILTER_IP_BUTTON {
            get {
                return ResourceManager.GetString("PS_STATUS_FILTER_IP_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 代理服务器正在监听端口.
        /// </summary>
        internal static string PS_STATUS_PORT_LISTEN {
            get {
                return ResourceManager.GetString("PS_STATUS_PORT_LISTEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 私服正在运行。.
        /// </summary>
        internal static string PS_STATUS_STARTED {
            get {
                return ResourceManager.GetString("PS_STATUS_STARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 私服已停止。.
        /// </summary>
        internal static string PS_STATUS_STOPPED {
            get {
                return ResourceManager.GetString("PS_STATUS_STOPPED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP地址.
        /// </summary>
        internal static string PS_STATUS_TEXT_IP_ADDRESS {
            get {
                return ResourceManager.GetString("PS_STATUS_TEXT_IP_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 子网掩码.
        /// </summary>
        internal static string PS_STATUS_TEXT_SUBNET_MASK {
            get {
                return ResourceManager.GetString("PS_STATUS_TEXT_SUBNET_MASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在更新所需文件…….
        /// </summary>
        internal static string PS_STATUS_UPDATING {
            get {
                return ResourceManager.GetString("PS_STATUS_UPDATING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通用设置.
        /// </summary>
        internal static string SETTINGS_CATEGORY_GENERAL {
            get {
                return ResourceManager.GetString("SETTINGS_CATEGORY_GENERAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 游戏内设置.
        /// </summary>
        internal static string SETTINGS_CATEGORY_IN_GAME {
            get {
                return ResourceManager.GetString("SETTINGS_CATEGORY_IN_GAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 安全设置.
        /// </summary>
        internal static string SETTINGS_CATEGORY_SECURITY {
            get {
                return ResourceManager.GetString("SETTINGS_CATEGORY_SECURITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新文件.
        /// </summary>
        internal static string SETTINGS_DIALOG_SAVE_FILE_TYPE {
            get {
                return ResourceManager.GetString("SETTINGS_DIALOG_SAVE_FILE_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将更新文件保存为…….
        /// </summary>
        internal static string SETTINGS_DIALOG_SAVE_TITLE {
            get {
                return ResourceManager.GetString("SETTINGS_DIALOG_SAVE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启动时自动检查更新.
        /// </summary>
        internal static string SETTINGS_GENERAL_AUTO_UPDATE {
            get {
                return ResourceManager.GetString("SETTINGS_GENERAL_AUTO_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 检查更新.
        /// </summary>
        internal static string SETTINGS_GENERAL_CHECK_UPDATE {
            get {
                return ResourceManager.GetString("SETTINGS_GENERAL_CHECK_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 检查.
        /// </summary>
        internal static string SETTINGS_GENERAL_CHECK_UPDATE_BUTTON {
            get {
                return ResourceManager.GetString("SETTINGS_GENERAL_CHECK_UPDATE_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在检查最新更新…….
        /// </summary>
        internal static string SETTINGS_GENERAL_CHECK_UPDATE_TEXT_CHECKING {
            get {
                return ResourceManager.GetString("SETTINGS_GENERAL_CHECK_UPDATE_TEXT_CHECKING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 有新更新可用。.
        /// </summary>
        internal static string SETTINGS_GENERAL_CHECK_UPDATE_TEXT_FOUND {
            get {
                return ResourceManager.GetString("SETTINGS_GENERAL_CHECK_UPDATE_TEXT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前为最新版本。.
        /// </summary>
        internal static string SETTINGS_GENERAL_CHECK_UPDATE_TEXT_NOT_FOUND {
            get {
                return ResourceManager.GetString("SETTINGS_GENERAL_CHECK_UPDATE_TEXT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 界面语言.
        /// </summary>
        internal static string SETTINGS_GENERAL_LANGUAGE {
            get {
                return ResourceManager.GetString("SETTINGS_GENERAL_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新通道.
        /// </summary>
        internal static string SETTINGS_GENERAL_UPDATE_CHANNEL {
            get {
                return ResourceManager.GetString("SETTINGS_GENERAL_UPDATE_CHANNEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下载更新.
        /// </summary>
        internal static string SETTINGS_GENERAL_UPDATE_NOW_BUTTON {
            get {
                return ResourceManager.GetString("SETTINGS_GENERAL_UPDATE_NOW_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无限道具.
        /// </summary>
        internal static string SETTINGS_IN_GAME_INFINITE_ITEMS {
            get {
                return ResourceManager.GetString("SETTINGS_IN_GAME_INFINITE_ITEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 游戏内剧情语言.
        /// </summary>
        internal static string SETTINGS_IN_GAME_LANGUAGE {
            get {
                return ResourceManager.GetString("SETTINGS_IN_GAME_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 敬请期待.
        /// </summary>
        internal static string SETTINGS_INFO_COMING_SOON {
            get {
                return ResourceManager.GetString("SETTINGS_INFO_COMING_SOON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重置后需要重新安装新证书.
        /// </summary>
        internal static string SETTINGS_INFO_REISSUE_CERT {
            get {
                return ResourceManager.GetString("SETTINGS_INFO_REISSUE_CERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 需要重启程序.
        /// </summary>
        internal static string SETTINGS_INFO_REQUIRE_RESTART {
            get {
                return ResourceManager.GetString("SETTINGS_INFO_REQUIRE_RESTART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 翻译由社区贡献.
        /// </summary>
        internal static string SETTINGS_INFO_TRANSLATION_PROVIDER {
            get {
                return ResourceManager.GetString("SETTINGS_INFO_TRANSLATION_PROVIDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用在线解密服务.
        /// </summary>
        internal static string SETTINGS_SECURITY_ONLINE_DECRYPTION {
            get {
                return ResourceManager.GetString("SETTINGS_SECURITY_ONLINE_DECRYPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重置.
        /// </summary>
        internal static string SETTINGS_SECURITY_REISSUE_BUTTON {
            get {
                return ResourceManager.GetString("SETTINGS_SECURITY_REISSUE_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重置SSL证书.
        /// </summary>
        internal static string SETTINGS_SECURITY_REISSUE_CERT {
            get {
                return ResourceManager.GetString("SETTINGS_SECURITY_REISSUE_CERT", resourceCulture);
            }
        }
    }
}
