//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yuyuyui.PrivateServer.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Yuyuyui.PrivateServer.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start
        ///Account
        ///Transfer.
        /// </summary>
        internal static string AT_BUTTON_START {
            get {
                return ResourceManager.GetString("AT_BUTTON_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop
        ///Account
        ///Transfer.
        /// </summary>
        internal static string AT_BUTTON_STOP {
            get {
                return ResourceManager.GetString("AT_BUTTON_STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note:.
        /// </summary>
        internal static string AT_NOTE {
            get {
                return ResourceManager.GetString("AT_NOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See the help page for more information..
        /// </summary>
        internal static string AT_NOTE_MORE_INFO {
            get {
                return ResourceManager.GetString("AT_NOTE_MORE_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only transfer one account at a time..
        /// </summary>
        internal static string AT_NOTE_ONE_ACCOUNT {
            get {
                return ResourceManager.GetString("AT_NOTE_ONE_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game must be restarted completely after each transfer..
        /// </summary>
        internal static string AT_NOTE_RESTART {
            get {
                return ResourceManager.GetString("AT_NOTE_RESTART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spirits.
        /// </summary>
        internal static string AT_TASK_ACCESSORIES {
            get {
                return ResourceManager.GetString("AT_TASK_ACCESSORIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cards.
        /// </summary>
        internal static string AT_TASK_CARDS {
            get {
                return ResourceManager.GetString("AT_TASK_CARDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affinities.
        /// </summary>
        internal static string AT_TASK_CHARACTER_FAMILIARITIES {
            get {
                return ResourceManager.GetString("AT_TASK_CHARACTER_FAMILIARITIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams.
        /// </summary>
        internal static string AT_TASK_DECKS {
            get {
                return ResourceManager.GetString("AT_TASK_DECKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common Data.
        /// </summary>
        internal static string AT_TASK_HEADER {
            get {
                return ResourceManager.GetString("AT_TASK_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string AT_TASK_ID {
            get {
                return ResourceManager.GetString("AT_TASK_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enhancement Items.
        /// </summary>
        internal static string AT_TASK_ITEMS_ENHANCEMENT {
            get {
                return ResourceManager.GetString("AT_TASK_ITEMS_ENHANCEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Items.
        /// </summary>
        internal static string AT_TASK_ITEMS_EVENT {
            get {
                return ResourceManager.GetString("AT_TASK_ITEMS_EVENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evolution Items.
        /// </summary>
        internal static string AT_TASK_ITEMS_EVOLUTION {
            get {
                return ResourceManager.GetString("AT_TASK_ITEMS_EVOLUTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stamina Items.
        /// </summary>
        internal static string AT_TASK_ITEMS_STAMINA {
            get {
                return ResourceManager.GetString("AT_TASK_ITEMS_STAMINA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titles.
        /// </summary>
        internal static string AT_TASK_ITEMS_TITLE {
            get {
                return ResourceManager.GetString("AT_TASK_ITEMS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string AT_TASK_PROFILE {
            get {
                return ResourceManager.GetString("AT_TASK_PROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        internal static string LAN_CODE {
            get {
                return ResourceManager.GetString("LAN_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Transfer Started!.
        /// </summary>
        internal static string LOG_AT_START {
            get {
                return ResourceManager.GetString("LOG_AT_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Transfer Stopped!.
        /// </summary>
        internal static string LOG_AT_STOP {
            get {
                return ResourceManager.GetString("LOG_AT_STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully transferred {0}.
        /// </summary>
        internal static string LOG_AT_TRANSFER_SUCCESS {
            get {
                return ResourceManager.GetString("LOG_AT_TRANSFER_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialized GUI..
        /// </summary>
        internal static string LOG_GUI_INITIALIZED {
            get {
                return ResourceManager.GetString("LOG_GUI_INITIALIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Server Started!.
        /// </summary>
        internal static string LOG_PS_START {
            get {
                return ResourceManager.GetString("LOG_PS_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Server Stopped!.
        /// </summary>
        internal static string LOG_PS_STOP {
            get {
                return ResourceManager.GetString("LOG_PS_STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABOUT.
        /// </summary>
        internal static string NAV_BUTTON_ABOUT {
            get {
                return ResourceManager.GetString("NAV_BUTTON_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HELP.
        /// </summary>
        internal static string NAV_BUTTON_HELP {
            get {
                return ResourceManager.GetString("NAV_BUTTON_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOG.
        /// </summary>
        internal static string NAV_BUTTON_LOG {
            get {
                return ResourceManager.GetString("NAV_BUTTON_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTINGS.
        /// </summary>
        internal static string NAV_BUTTON_SETTINGS {
            get {
                return ResourceManager.GetString("NAV_BUTTON_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STATUS.
        /// </summary>
        internal static string NAV_BUTTON_STATUS {
            get {
                return ResourceManager.GetString("NAV_BUTTON_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRANSFER.
        /// </summary>
        internal static string NAV_BUTTON_TRANSFER {
            get {
                return ResourceManager.GetString("NAV_BUTTON_TRANSFER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Server for Mobile Game YUYUYUI.
        /// </summary>
        internal static string PROJ_DESC {
            get {
                return ResourceManager.GetString("PROJ_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to START.
        /// </summary>
        internal static string PS_BUTTON_START {
            get {
                return ResourceManager.GetString("PS_BUTTON_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start the Private Server.
        /// </summary>
        internal static string PS_BUTTON_START_DESC {
            get {
                return ResourceManager.GetString("PS_BUTTON_START_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STOP.
        /// </summary>
        internal static string PS_BUTTON_STOP {
            get {
                return ResourceManager.GetString("PS_BUTTON_STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Server is running.
        /// </summary>
        internal static string PS_BUTTON_STOP_DESC {
            get {
                return ResourceManager.GetString("PS_BUTTON_STOP_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRANSFER.
        /// </summary>
        internal static string PS_BUTTON_TRANSFER {
            get {
                return ResourceManager.GetString("PS_BUTTON_TRANSFER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferring Account....
        /// </summary>
        internal static string PS_BUTTON_TRANSFER_DESC {
            get {
                return ResourceManager.GetString("PS_BUTTON_TRANSFER_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATING.
        /// </summary>
        internal static string PS_BUTTON_UPDATE {
            get {
                return ResourceManager.GetString("PS_BUTTON_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating Required Files....
        /// </summary>
        internal static string PS_BUTTON_UPDATE_DESC {
            get {
                return ResourceManager.GetString("PS_BUTTON_UPDATE_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to Use the Account Transfer Tool.
        /// </summary>
        internal static string PS_HELP_AT {
            get {
                return ResourceManager.GetString("PS_HELP_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string PS_HELP_BACK_BUTTON {
            get {
                return ResourceManager.GetString("PS_HELP_BACK_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to Install an SSL Certificate (Android).
        /// </summary>
        internal static string PS_HELP_CERT_ANDROID {
            get {
                return ResourceManager.GetString("PS_HELP_CERT_ANDROID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to Install an SSL Certificate (iOS).
        /// </summary>
        internal static string PS_HELP_CERT_IOS {
            get {
                return ResourceManager.GetString("PS_HELP_CERT_IOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is This Project.
        /// </summary>
        internal static string PS_HELP_INTRO {
            get {
                return ResourceManager.GetString("PS_HELP_INTRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to Connect to the Proxy.
        /// </summary>
        internal static string PS_HELP_PROXY {
            get {
                return ResourceManager.GetString("PS_HELP_PROXY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to Use Private Server.
        /// </summary>
        internal static string PS_HELP_PS {
            get {
                return ResourceManager.GetString("PS_HELP_PS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which one should I use?.
        /// </summary>
        internal static string PS_STATUS_CHOOSE_IP {
            get {
                return ResourceManager.GetString("PS_STATUS_CHOOSE_IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use one of the following addresses as your proxy:.
        /// </summary>
        internal static string PS_STATUS_CHOOSE_MULTIPLE {
            get {
                return ResourceManager.GetString("PS_STATUS_CHOOSE_MULTIPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no address can be used as your proxy!.
        /// </summary>
        internal static string PS_STATUS_CHOOSE_NONE {
            get {
                return ResourceManager.GetString("PS_STATUS_CHOOSE_NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the following address as your proxy:.
        /// </summary>
        internal static string PS_STATUS_CHOOSE_SINGLE {
            get {
                return ResourceManager.GetString("PS_STATUS_CHOOSE_SINGLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Filter.
        /// </summary>
        internal static string PS_STATUS_CLEAR_FILTER_BUTTON {
            get {
                return ResourceManager.GetString("PS_STATUS_CLEAR_FILTER_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string PS_STATUS_FILTER_IP_BUTTON {
            get {
                return ResourceManager.GetString("PS_STATUS_FILTER_IP_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy is listening at port .
        /// </summary>
        internal static string PS_STATUS_PORT_LISTEN {
            get {
                return ResourceManager.GetString("PS_STATUS_PORT_LISTEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Server is currently running..
        /// </summary>
        internal static string PS_STATUS_STARTED {
            get {
                return ResourceManager.GetString("PS_STATUS_STARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Server is not running..
        /// </summary>
        internal static string PS_STATUS_STOPPED {
            get {
                return ResourceManager.GetString("PS_STATUS_STOPPED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address.
        /// </summary>
        internal static string PS_STATUS_TEXT_IP_ADDRESS {
            get {
                return ResourceManager.GetString("PS_STATUS_TEXT_IP_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subnet Mask.
        /// </summary>
        internal static string PS_STATUS_TEXT_SUBNET_MASK {
            get {
                return ResourceManager.GetString("PS_STATUS_TEXT_SUBNET_MASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Transfer is in progress..
        /// </summary>
        internal static string PS_STATUS_TRANSFERRING {
            get {
                return ResourceManager.GetString("PS_STATUS_TRANSFERRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Server is updating required files....
        /// </summary>
        internal static string PS_STATUS_UPDATING {
            get {
                return ResourceManager.GetString("PS_STATUS_UPDATING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yuyuyui Private Server.
        /// </summary>
        internal static string WINDOW_TITLE {
            get {
                return ResourceManager.GetString("WINDOW_TITLE", resourceCulture);
            }
        }
    }
}
