//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yuyuyui.PrivateServer.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Yuyuyui.PrivateServer.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start
        ///Account
        ///Transfer.
        /// </summary>
        internal static string AT_BUTTON_START {
            get {
                return ResourceManager.GetString("AT_BUTTON_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop
        ///Account
        ///Transfer.
        /// </summary>
        internal static string AT_BUTTON_STOP {
            get {
                return ResourceManager.GetString("AT_BUTTON_STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: .
        /// </summary>
        internal static string AT_NOTE {
            get {
                return ResourceManager.GetString("AT_NOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See the help page for more information..
        /// </summary>
        internal static string AT_NOTE_MORE_INFO {
            get {
                return ResourceManager.GetString("AT_NOTE_MORE_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only transfer one account at a time..
        /// </summary>
        internal static string AT_NOTE_ONE_ACCOUNT {
            get {
                return ResourceManager.GetString("AT_NOTE_ONE_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game must be restarted completely after each transfer..
        /// </summary>
        internal static string AT_NOTE_RESTART {
            get {
                return ResourceManager.GetString("AT_NOTE_RESTART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spirits.
        /// </summary>
        internal static string AT_TASK_ACCESSORIES {
            get {
                return ResourceManager.GetString("AT_TASK_ACCESSORIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cards.
        /// </summary>
        internal static string AT_TASK_CARDS {
            get {
                return ResourceManager.GetString("AT_TASK_CARDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affinities.
        /// </summary>
        internal static string AT_TASK_CHARACTER_FAMILIARITIES {
            get {
                return ResourceManager.GetString("AT_TASK_CHARACTER_FAMILIARITIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams.
        /// </summary>
        internal static string AT_TASK_DECKS {
            get {
                return ResourceManager.GetString("AT_TASK_DECKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common Data.
        /// </summary>
        internal static string AT_TASK_HEADER {
            get {
                return ResourceManager.GetString("AT_TASK_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string AT_TASK_ID {
            get {
                return ResourceManager.GetString("AT_TASK_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enhancement Items.
        /// </summary>
        internal static string AT_TASK_ITEMS_ENHANCEMENT {
            get {
                return ResourceManager.GetString("AT_TASK_ITEMS_ENHANCEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Items.
        /// </summary>
        internal static string AT_TASK_ITEMS_EVENT {
            get {
                return ResourceManager.GetString("AT_TASK_ITEMS_EVENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evolution Items.
        /// </summary>
        internal static string AT_TASK_ITEMS_EVOLUTION {
            get {
                return ResourceManager.GetString("AT_TASK_ITEMS_EVOLUTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stamina Items.
        /// </summary>
        internal static string AT_TASK_ITEMS_STAMINA {
            get {
                return ResourceManager.GetString("AT_TASK_ITEMS_STAMINA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titles.
        /// </summary>
        internal static string AT_TASK_ITEMS_TITLE {
            get {
                return ResourceManager.GetString("AT_TASK_ITEMS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string AT_TASK_PROFILE {
            get {
                return ResourceManager.GetString("AT_TASK_PROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        internal static string LAN_CODE {
            get {
                return ResourceManager.GetString("LAN_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow System.
        /// </summary>
        internal static string LAN_DEFAULT {
            get {
                return ResourceManager.GetString("LAN_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All transfer tasks have completed. Program will exit in 10 seconds..
        /// </summary>
        internal static string LOG_AT_FINISH_EXIT {
            get {
                return ResourceManager.GetString("LOG_AT_FINISH_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got Titles, {0} in Total.
        /// </summary>
        internal static string LOG_AT_GET_TITLES {
            get {
                return ResourceManager.GetString("LOG_AT_GET_TITLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got Accessories, {0} in Total.
        /// </summary>
        internal static string LOG_AT_GOT_ACCESSORIES {
            get {
                return ResourceManager.GetString("LOG_AT_GOT_ACCESSORIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got Cards, {0} in Total.
        /// </summary>
        internal static string LOG_AT_GOT_CARDS {
            get {
                return ResourceManager.GetString("LOG_AT_GOT_CARDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got Character Affinities.
        /// </summary>
        internal static string LOG_AT_GOT_CHARACTER_FAMILIARITIES {
            get {
                return ResourceManager.GetString("LOG_AT_GOT_CHARACTER_FAMILIARITIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got User Code: {0}.
        /// </summary>
        internal static string LOG_AT_GOT_CODE {
            get {
                return ResourceManager.GetString("LOG_AT_GOT_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got Decks.
        /// </summary>
        internal static string LOG_AT_GOT_DECKS {
            get {
                return ResourceManager.GetString("LOG_AT_GOT_DECKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got User Data: Level {0}, EXP: {1}, Money: {2}.
        /// </summary>
        internal static string LOG_AT_GOT_HEADER {
            get {
                return ResourceManager.GetString("LOG_AT_GOT_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got {0}.
        /// </summary>
        internal static string LOG_AT_GOT_ITEMS {
            get {
                return ResourceManager.GetString("LOG_AT_GOT_ITEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got User Profile: Nickname: {0}, Comment: {1}.
        /// </summary>
        internal static string LOG_AT_GOT_USER_INFO {
            get {
                return ResourceManager.GetString("LOG_AT_GOT_USER_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got User UUID: {0}.
        /// </summary>
        internal static string LOG_AT_GOT_UUID {
            get {
                return ResourceManager.GetString("LOG_AT_GOT_UUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Transfer Started!.
        /// </summary>
        internal static string LOG_AT_START {
            get {
                return ResourceManager.GetString("LOG_AT_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Transfer Stopped!.
        /// </summary>
        internal static string LOG_AT_STOP {
            get {
                return ResourceManager.GetString("LOG_AT_STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully transferred {0}.
        /// </summary>
        internal static string LOG_AT_TRANSFER_SUCCESS {
            get {
                return ResourceManager.GetString("LOG_AT_TRANSFER_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialized GUI..
        /// </summary>
        internal static string LOG_GUI_INITIALIZED {
            get {
                return ResourceManager.GetString("LOG_GUI_INITIALIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LibGK Lambda Call Failed! .
        /// </summary>
        internal static string LOG_LIBGK_LAMBDA_FAILED {
            get {
                return ResourceManager.GetString("LOG_LIBGK_LAMBDA_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listening at .
        /// </summary>
        internal static string LOG_LISTENING_AT {
            get {
                return ResourceManager.GetString("LOG_LISTENING_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned new accessory with master_id = {0}.
        /// </summary>
        internal static string LOG_PS_ACCESSORY_ASSIGN_NEW {
            get {
                return ResourceManager.GetString("LOG_PS_ACCESSORY_ASSIGN_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account {0} Banned.
        /// </summary>
        internal static string LOG_PS_ACCOUNT_BANNED {
            get {
                return ResourceManager.GetString("LOG_PS_ACCOUNT_BANNED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banning Account {0}.
        /// </summary>
        internal static string LOG_PS_ACCOUNT_BANNING {
            get {
                return ResourceManager.GetString("LOG_PS_ACCOUNT_BANNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;APIError&gt; .
        /// </summary>
        internal static string LOG_PS_API_ERROR_TEMPLATE {
            get {
                return ResourceManager.GetString("LOG_PS_API_ERROR_TEMPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Not Implemented: .
        /// </summary>
        internal static string LOG_PS_API_NOT_IMPLEMENTED {
            get {
                return ResourceManager.GetString("LOG_PS_API_NOT_IMPLEMENTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned new card with master_id = {0}.
        /// </summary>
        internal static string LOG_PS_CARD_ASSIGN_NEW {
            get {
                return ResourceManager.GetString("LOG_PS_CARD_ASSIGN_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created session for player {0} with Session ID = {1}, Session Key = {2}.
        /// </summary>
        internal static string LOG_PS_CREATE_SESSION {
            get {
                return ResourceManager.GetString("LOG_PS_CREATE_SESSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Enter key to exit the program at any time..
        /// </summary>
        internal static string LOG_PS_ENTER_TO_EXIT {
            get {
                return ResourceManager.GetString("LOG_PS_ENTER_TO_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player {0} and {1} are friends now!.
        /// </summary>
        internal static string LOG_PS_FRIEND_REQUEST_ACCEPTED {
            get {
                return ResourceManager.GetString("LOG_PS_FRIEND_REQUEST_ACCEPTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created friend request {0} ({1}=&gt;{2}).
        /// </summary>
        internal static string LOG_PS_FRIEND_REQUEST_CREATED {
            get {
                return ResourceManager.GetString("LOG_PS_FRIEND_REQUEST_CREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend request {0} ({1}=&gt;{2}) deleted!.
        /// </summary>
        internal static string LOG_PS_FRIEND_REQUEST_DELETED {
            get {
                return ResourceManager.GetString("LOG_PS_FRIEND_REQUEST_DELETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found an existed friend request {0} ({1}=&gt;{2}).
        /// </summary>
        internal static string LOG_PS_FRIEND_REQUEST_FOUND {
            get {
                return ResourceManager.GetString("LOG_PS_FRIEND_REQUEST_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player {0} rejected the friend request from {1}.
        /// </summary>
        internal static string LOG_PS_FRIEND_REQUEST_REJECTED {
            get {
                return ResourceManager.GetString("LOG_PS_FRIEND_REQUEST_REJECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend request {0} removed from player {1}.
        /// </summary>
        internal static string LOG_PS_FRIEND_REQUEST_REMOVED {
            get {
                return ResourceManager.GetString("LOG_PS_FRIEND_REQUEST_REMOVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend request {0} sent to player {1}.
        /// </summary>
        internal static string LOG_PS_FRIEND_REQUEST_SENT {
            get {
                return ResourceManager.GetString("LOG_PS_FRIEND_REQUEST_SENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown status, shouldn&apos;t be here!.
        /// </summary>
        internal static string LOG_PS_FRIEND_REQUEST_UNKNOWN {
            get {
                return ResourceManager.GetString("LOG_PS_FRIEND_REQUEST_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got connection from UUID {0}.
        /// </summary>
        internal static string LOG_PS_GOT_CONNECTION {
            get {
                return ResourceManager.GetString("LOG_PS_GOT_CONNECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading {0}....
        /// </summary>
        internal static string LOG_PS_LOCAL_DATA_DOWNLOADING {
            get {
                return ResourceManager.GetString("LOG_PS_LOCAL_DATA_DOWNLOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All data files are up to date.
        /// </summary>
        internal static string LOG_PS_LOCAL_DATA_UP_TO_DATE {
            get {
                return ResourceManager.GetString("LOG_PS_LOCAL_DATA_UP_TO_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated {0} file(s).
        /// </summary>
        internal static string LOG_PS_LOCAL_DATA_UPDATED {
            get {
                return ResourceManager.GetString("LOG_PS_LOCAL_DATA_UPDATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating required local resources....
        /// </summary>
        internal static string LOG_PS_LOCAL_DATA_UPDATING {
            get {
                return ResourceManager.GetString("LOG_PS_LOCAL_DATA_UPDATING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirected to the unofficial public API Server.
        /// </summary>
        internal static string LOG_PS_REDIRECT_API {
            get {
                return ResourceManager.GetString("LOG_PS_REDIRECT_API", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered new player {0}.
        /// </summary>
        internal static string LOG_PS_REGISTER_NEW_PLAYER {
            get {
                return ResourceManager.GetString("LOG_PS_REGISTER_NEW_PLAYER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario language is {0}.
        /// </summary>
        internal static string LOG_PS_SCENARIO_LANGUAGE {
            get {
                return ResourceManager.GetString("LOG_PS_SCENARIO_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Server Started!.
        /// </summary>
        internal static string LOG_PS_START {
            get {
                return ResourceManager.GetString("LOG_PS_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Server Stopped!.
        /// </summary>
        internal static string LOG_PS_STOP {
            get {
                return ResourceManager.GetString("LOG_PS_STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for application update on branch {0}....
        /// </summary>
        internal static string LOG_UPDATE_CHECKING {
            get {
                return ResourceManager.GetString("LOG_UPDATE_CHECKING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded new update file at {0}.
        /// </summary>
        internal static string LOG_UPDATE_DOWNLOADED {
            get {
                return ResourceManager.GetString("LOG_UPDATE_DOWNLOADED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found new version: commit {0} on branch {1}.
        /// </summary>
        internal static string LOG_UPDATE_FOUND {
            get {
                return ResourceManager.GetString("LOG_UPDATE_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No new version found..
        /// </summary>
        internal static string LOG_UPDATE_NOT_FOUND {
            get {
                return ResourceManager.GetString("LOG_UPDATE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        internal static string LOG_VERSION {
            get {
                return ResourceManager.GetString("LOG_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABOUT.
        /// </summary>
        internal static string NAV_BUTTON_ABOUT {
            get {
                return ResourceManager.GetString("NAV_BUTTON_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HELP.
        /// </summary>
        internal static string NAV_BUTTON_HELP {
            get {
                return ResourceManager.GetString("NAV_BUTTON_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOG.
        /// </summary>
        internal static string NAV_BUTTON_LOG {
            get {
                return ResourceManager.GetString("NAV_BUTTON_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTINGS.
        /// </summary>
        internal static string NAV_BUTTON_SETTINGS {
            get {
                return ResourceManager.GetString("NAV_BUTTON_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STATUS.
        /// </summary>
        internal static string NAV_BUTTON_STATUS {
            get {
                return ResourceManager.GetString("NAV_BUTTON_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRANSFER.
        /// </summary>
        internal static string NAV_BUTTON_TRANSFER {
            get {
                return ResourceManager.GetString("NAV_BUTTON_TRANSFER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Transfer Tool for Mobile Game YUYUYUI.
        /// </summary>
        internal static string PROJ_DESC_EUCALYPTUS {
            get {
                return ResourceManager.GetString("PROJ_DESC_EUCALYPTUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Server for Mobile Game YUYUYUI.
        /// </summary>
        internal static string PROJ_DESC_JINCHOGE {
            get {
                return ResourceManager.GetString("PROJ_DESC_JINCHOGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to START.
        /// </summary>
        internal static string PS_BUTTON_START {
            get {
                return ResourceManager.GetString("PS_BUTTON_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start the Private Server.
        /// </summary>
        internal static string PS_BUTTON_START_DESC {
            get {
                return ResourceManager.GetString("PS_BUTTON_START_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STOP.
        /// </summary>
        internal static string PS_BUTTON_STOP {
            get {
                return ResourceManager.GetString("PS_BUTTON_STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Server is running.
        /// </summary>
        internal static string PS_BUTTON_STOP_DESC {
            get {
                return ResourceManager.GetString("PS_BUTTON_STOP_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRANSFER.
        /// </summary>
        internal static string PS_BUTTON_TRANSFER {
            get {
                return ResourceManager.GetString("PS_BUTTON_TRANSFER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferring Account....
        /// </summary>
        internal static string PS_BUTTON_TRANSFER_DESC {
            get {
                return ResourceManager.GetString("PS_BUTTON_TRANSFER_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATING.
        /// </summary>
        internal static string PS_BUTTON_UPDATE {
            get {
                return ResourceManager.GetString("PS_BUTTON_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating Required Files....
        /// </summary>
        internal static string PS_BUTTON_UPDATE_DESC {
            get {
                return ResourceManager.GetString("PS_BUTTON_UPDATE_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to Use Eucalyptus (Account Transfer).
        /// </summary>
        internal static string PS_HELP_AT {
            get {
                return ResourceManager.GetString("PS_HELP_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string PS_HELP_BACK_BUTTON {
            get {
                return ResourceManager.GetString("PS_HELP_BACK_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to Install an SSL Certificate (Android).
        /// </summary>
        internal static string PS_HELP_CERT_ANDROID {
            get {
                return ResourceManager.GetString("PS_HELP_CERT_ANDROID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to Install an SSL Certificate (iOS).
        /// </summary>
        internal static string PS_HELP_CERT_IOS {
            get {
                return ResourceManager.GetString("PS_HELP_CERT_IOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is This Project.
        /// </summary>
        internal static string PS_HELP_INTRO {
            get {
                return ResourceManager.GetString("PS_HELP_INTRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to Connect to the Proxy.
        /// </summary>
        internal static string PS_HELP_PROXY {
            get {
                return ResourceManager.GetString("PS_HELP_PROXY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to Use Jinchōge (Private Server).
        /// </summary>
        internal static string PS_HELP_PS {
            get {
                return ResourceManager.GetString("PS_HELP_PS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which one should I use?.
        /// </summary>
        internal static string PS_STATUS_CHOOSE_IP {
            get {
                return ResourceManager.GetString("PS_STATUS_CHOOSE_IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use one of the following addresses as your proxy:.
        /// </summary>
        internal static string PS_STATUS_CHOOSE_MULTIPLE {
            get {
                return ResourceManager.GetString("PS_STATUS_CHOOSE_MULTIPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no address can be used as your proxy!.
        /// </summary>
        internal static string PS_STATUS_CHOOSE_NONE {
            get {
                return ResourceManager.GetString("PS_STATUS_CHOOSE_NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the following address as your proxy:.
        /// </summary>
        internal static string PS_STATUS_CHOOSE_SINGLE {
            get {
                return ResourceManager.GetString("PS_STATUS_CHOOSE_SINGLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Filter.
        /// </summary>
        internal static string PS_STATUS_CLEAR_FILTER_BUTTON {
            get {
                return ResourceManager.GetString("PS_STATUS_CLEAR_FILTER_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string PS_STATUS_FILTER_IP_BUTTON {
            get {
                return ResourceManager.GetString("PS_STATUS_FILTER_IP_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy is listening at port .
        /// </summary>
        internal static string PS_STATUS_PORT_LISTEN {
            get {
                return ResourceManager.GetString("PS_STATUS_PORT_LISTEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Server is currently running..
        /// </summary>
        internal static string PS_STATUS_STARTED {
            get {
                return ResourceManager.GetString("PS_STATUS_STARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Server is not running..
        /// </summary>
        internal static string PS_STATUS_STOPPED {
            get {
                return ResourceManager.GetString("PS_STATUS_STOPPED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address.
        /// </summary>
        internal static string PS_STATUS_TEXT_IP_ADDRESS {
            get {
                return ResourceManager.GetString("PS_STATUS_TEXT_IP_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subnet Mask.
        /// </summary>
        internal static string PS_STATUS_TEXT_SUBNET_MASK {
            get {
                return ResourceManager.GetString("PS_STATUS_TEXT_SUBNET_MASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Transfer is in progress..
        /// </summary>
        internal static string PS_STATUS_TRANSFERRING {
            get {
                return ResourceManager.GetString("PS_STATUS_TRANSFERRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Server is updating required files....
        /// </summary>
        internal static string PS_STATUS_UPDATING {
            get {
                return ResourceManager.GetString("PS_STATUS_UPDATING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Settings.
        /// </summary>
        internal static string SETTINGS_CATEGORY_GENERAL {
            get {
                return ResourceManager.GetString("SETTINGS_CATEGORY_GENERAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In-Game Settings.
        /// </summary>
        internal static string SETTINGS_CATEGORY_IN_GAME {
            get {
                return ResourceManager.GetString("SETTINGS_CATEGORY_IN_GAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Settings.
        /// </summary>
        internal static string SETTINGS_CATEGORY_SECURITY {
            get {
                return ResourceManager.GetString("SETTINGS_CATEGORY_SECURITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update File.
        /// </summary>
        internal static string SETTINGS_DIALOG_SAVE_FILE_TYPE {
            get {
                return ResourceManager.GetString("SETTINGS_DIALOG_SAVE_FILE_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Update File As....
        /// </summary>
        internal static string SETTINGS_DIALOG_SAVE_TITLE {
            get {
                return ResourceManager.GetString("SETTINGS_DIALOG_SAVE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Auto Check Update.
        /// </summary>
        internal static string SETTINGS_GENERAL_AUTO_UPDATE {
            get {
                return ResourceManager.GetString("SETTINGS_GENERAL_AUTO_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Update.
        /// </summary>
        internal static string SETTINGS_GENERAL_CHECK_UPDATE {
            get {
                return ResourceManager.GetString("SETTINGS_GENERAL_CHECK_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check.
        /// </summary>
        internal static string SETTINGS_GENERAL_CHECK_UPDATE_BUTTON {
            get {
                return ResourceManager.GetString("SETTINGS_GENERAL_CHECK_UPDATE_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for latest updates....
        /// </summary>
        internal static string SETTINGS_GENERAL_CHECK_UPDATE_TEXT_CHECKING {
            get {
                return ResourceManager.GetString("SETTINGS_GENERAL_CHECK_UPDATE_TEXT_CHECKING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New update avaliable..
        /// </summary>
        internal static string SETTINGS_GENERAL_CHECK_UPDATE_TEXT_FOUND {
            get {
                return ResourceManager.GetString("SETTINGS_GENERAL_CHECK_UPDATE_TEXT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are using the latest version..
        /// </summary>
        internal static string SETTINGS_GENERAL_CHECK_UPDATE_TEXT_NOT_FOUND {
            get {
                return ResourceManager.GetString("SETTINGS_GENERAL_CHECK_UPDATE_TEXT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface Language.
        /// </summary>
        internal static string SETTINGS_GENERAL_LANGUAGE {
            get {
                return ResourceManager.GetString("SETTINGS_GENERAL_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Channel.
        /// </summary>
        internal static string SETTINGS_GENERAL_UPDATE_CHANNEL {
            get {
                return ResourceManager.GetString("SETTINGS_GENERAL_UPDATE_CHANNEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Update.
        /// </summary>
        internal static string SETTINGS_GENERAL_UPDATE_NOW_BUTTON {
            get {
                return ResourceManager.GetString("SETTINGS_GENERAL_UPDATE_NOW_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario Language.
        /// </summary>
        internal static string SETTINGS_IN_GAME_LANGUAGE {
            get {
                return ResourceManager.GetString("SETTINGS_IN_GAME_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requires Reinstall the Certificate.
        /// </summary>
        internal static string SETTINGS_INFO_REISSUE_CERT {
            get {
                return ResourceManager.GetString("SETTINGS_INFO_REISSUE_CERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requires Restart.
        /// </summary>
        internal static string SETTINGS_INFO_REQUIRE_RESTART {
            get {
                return ResourceManager.GetString("SETTINGS_INFO_REQUIRE_RESTART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translations Provided by Community Contributions.
        /// </summary>
        internal static string SETTINGS_INFO_TRANSLATION_PROVIDER {
            get {
                return ResourceManager.GetString("SETTINGS_INFO_TRANSLATION_PROVIDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Online Decryption.
        /// </summary>
        internal static string SETTINGS_SECURITY_ONLINE_DECRYPTION {
            get {
                return ResourceManager.GetString("SETTINGS_SECURITY_ONLINE_DECRYPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reissue.
        /// </summary>
        internal static string SETTINGS_SECURITY_REISSUE_BUTTON {
            get {
                return ResourceManager.GetString("SETTINGS_SECURITY_REISSUE_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reissue SSL Certificate.
        /// </summary>
        internal static string SETTINGS_SECURITY_REISSUE_CERT {
            get {
                return ResourceManager.GetString("SETTINGS_SECURITY_REISSUE_CERT", resourceCulture);
            }
        }
    }
}
