//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yuyuyui.PrivateServer.Localization {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_zh {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_zh() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Yuyuyui.PrivateServer.Localization.Resources_zh", typeof(Resources_zh).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string PS_BUTTON_START {
            get {
                return ResourceManager.GetString("PS_BUTTON_START", resourceCulture);
            }
        }
        
        internal static string LOG_PS_START {
            get {
                return ResourceManager.GetString("LOG_PS_START", resourceCulture);
            }
        }
        
        internal static string LOG_PS_STOP {
            get {
                return ResourceManager.GetString("LOG_PS_STOP", resourceCulture);
            }
        }
        
        internal static string PS_BUTTON_START_DESC {
            get {
                return ResourceManager.GetString("PS_BUTTON_START_DESC", resourceCulture);
            }
        }
        
        internal static string PS_BUTTON_STOP {
            get {
                return ResourceManager.GetString("PS_BUTTON_STOP", resourceCulture);
            }
        }
        
        internal static string PS_BUTTON_STOP_DESC {
            get {
                return ResourceManager.GetString("PS_BUTTON_STOP_DESC", resourceCulture);
            }
        }
        
        internal static string PS_BUTTON_TRANSFER {
            get {
                return ResourceManager.GetString("PS_BUTTON_TRANSFER", resourceCulture);
            }
        }
        
        internal static string PS_BUTTON_TRANSFER_DESC {
            get {
                return ResourceManager.GetString("PS_BUTTON_TRANSFER_DESC", resourceCulture);
            }
        }
        
        internal static string PS_BUTTON_UPDATE {
            get {
                return ResourceManager.GetString("PS_BUTTON_UPDATE", resourceCulture);
            }
        }
        
        internal static string PS_BUTTON_UPDATE_DESC {
            get {
                return ResourceManager.GetString("PS_BUTTON_UPDATE_DESC", resourceCulture);
            }
        }
        
        internal static string NAV_BUTTON_ABOUT {
            get {
                return ResourceManager.GetString("NAV_BUTTON_ABOUT", resourceCulture);
            }
        }
        
        internal static string NAV_BUTTON_HELP {
            get {
                return ResourceManager.GetString("NAV_BUTTON_HELP", resourceCulture);
            }
        }
        
        internal static string NAV_BUTTON_LOG {
            get {
                return ResourceManager.GetString("NAV_BUTTON_LOG", resourceCulture);
            }
        }
        
        internal static string NAV_BUTTON_SETTINGS {
            get {
                return ResourceManager.GetString("NAV_BUTTON_SETTINGS", resourceCulture);
            }
        }
        
        internal static string NAV_BUTTON_STATUS {
            get {
                return ResourceManager.GetString("NAV_BUTTON_STATUS", resourceCulture);
            }
        }
        
        internal static string NAV_BUTTON_TRANSFER {
            get {
                return ResourceManager.GetString("NAV_BUTTON_TRANSFER", resourceCulture);
            }
        }
        
        internal static string PROJ_DESC_JINCHOGE {
            get {
                return ResourceManager.GetString("PROJ_DESC_JINCHOGE", resourceCulture);
            }
        }
        
        internal static string AT_BUTTON_START {
            get {
                return ResourceManager.GetString("AT_BUTTON_START", resourceCulture);
            }
        }
        
        internal static string AT_BUTTON_STOP {
            get {
                return ResourceManager.GetString("AT_BUTTON_STOP", resourceCulture);
            }
        }
        
        internal static string AT_NOTE {
            get {
                return ResourceManager.GetString("AT_NOTE", resourceCulture);
            }
        }
        
        internal static string AT_NOTE_MORE_INFO {
            get {
                return ResourceManager.GetString("AT_NOTE_MORE_INFO", resourceCulture);
            }
        }
        
        internal static string AT_NOTE_ONE_ACCOUNT {
            get {
                return ResourceManager.GetString("AT_NOTE_ONE_ACCOUNT", resourceCulture);
            }
        }
        
        internal static string AT_NOTE_RESTART {
            get {
                return ResourceManager.GetString("AT_NOTE_RESTART", resourceCulture);
            }
        }
        
        internal static string AT_TASK_ACCESSORIES {
            get {
                return ResourceManager.GetString("AT_TASK_ACCESSORIES", resourceCulture);
            }
        }
        
        internal static string AT_TASK_CARDS {
            get {
                return ResourceManager.GetString("AT_TASK_CARDS", resourceCulture);
            }
        }
        
        internal static string AT_TASK_CHARACTER_FAMILIARITIES {
            get {
                return ResourceManager.GetString("AT_TASK_CHARACTER_FAMILIARITIES", resourceCulture);
            }
        }
        
        internal static string AT_TASK_DECKS {
            get {
                return ResourceManager.GetString("AT_TASK_DECKS", resourceCulture);
            }
        }
        
        internal static string AT_TASK_HEADER {
            get {
                return ResourceManager.GetString("AT_TASK_HEADER", resourceCulture);
            }
        }
        
        internal static string AT_TASK_ID {
            get {
                return ResourceManager.GetString("AT_TASK_ID", resourceCulture);
            }
        }
        
        internal static string AT_TASK_PROFILE {
            get {
                return ResourceManager.GetString("AT_TASK_PROFILE", resourceCulture);
            }
        }
        
        internal static string AT_TASK_ITEMS_ENHANCEMENT {
            get {
                return ResourceManager.GetString("AT_TASK_ITEMS_ENHANCEMENT", resourceCulture);
            }
        }
        
        internal static string AT_TASK_ITEMS_EVENT {
            get {
                return ResourceManager.GetString("AT_TASK_ITEMS_EVENT", resourceCulture);
            }
        }
        
        internal static string AT_TASK_ITEMS_STAMINA {
            get {
                return ResourceManager.GetString("AT_TASK_ITEMS_STAMINA", resourceCulture);
            }
        }
        
        internal static string AT_TASK_ITEMS_EVOLUTION {
            get {
                return ResourceManager.GetString("AT_TASK_ITEMS_EVOLUTION", resourceCulture);
            }
        }
        
        internal static string AT_TASK_ITEMS_TITLE {
            get {
                return ResourceManager.GetString("AT_TASK_ITEMS_TITLE", resourceCulture);
            }
        }
        
        internal static string LOG_AT_START {
            get {
                return ResourceManager.GetString("LOG_AT_START", resourceCulture);
            }
        }
        
        internal static string LOG_AT_STOP {
            get {
                return ResourceManager.GetString("LOG_AT_STOP", resourceCulture);
            }
        }
        
        internal static string LOG_AT_TRANSFER_SUCCESS {
            get {
                return ResourceManager.GetString("LOG_AT_TRANSFER_SUCCESS", resourceCulture);
            }
        }
        
        internal static string PS_STATUS_STARTED {
            get {
                return ResourceManager.GetString("PS_STATUS_STARTED", resourceCulture);
            }
        }
        
        internal static string PS_STATUS_STOPPED {
            get {
                return ResourceManager.GetString("PS_STATUS_STOPPED", resourceCulture);
            }
        }
        
        internal static string PS_STATUS_TRANSFERRING {
            get {
                return ResourceManager.GetString("PS_STATUS_TRANSFERRING", resourceCulture);
            }
        }
        
        internal static string PS_STATUS_UPDATING {
            get {
                return ResourceManager.GetString("PS_STATUS_UPDATING", resourceCulture);
            }
        }
        
        internal static string PS_STATUS_PORT_LISTEN {
            get {
                return ResourceManager.GetString("PS_STATUS_PORT_LISTEN", resourceCulture);
            }
        }
        
        internal static string PS_STATUS_CHOOSE_IP {
            get {
                return ResourceManager.GetString("PS_STATUS_CHOOSE_IP", resourceCulture);
            }
        }
        
        internal static string PS_STATUS_CLEAR_FILTER_BUTTON {
            get {
                return ResourceManager.GetString("PS_STATUS_CLEAR_FILTER_BUTTON", resourceCulture);
            }
        }
        
        internal static string PS_STATUS_FILTER_IP_BUTTON {
            get {
                return ResourceManager.GetString("PS_STATUS_FILTER_IP_BUTTON", resourceCulture);
            }
        }
        
        internal static string PS_STATUS_CHOOSE_MULTIPLE {
            get {
                return ResourceManager.GetString("PS_STATUS_CHOOSE_MULTIPLE", resourceCulture);
            }
        }
        
        internal static string PS_STATUS_CHOOSE_NONE {
            get {
                return ResourceManager.GetString("PS_STATUS_CHOOSE_NONE", resourceCulture);
            }
        }
        
        internal static string PS_STATUS_CHOOSE_SINGLE {
            get {
                return ResourceManager.GetString("PS_STATUS_CHOOSE_SINGLE", resourceCulture);
            }
        }
        
        internal static string PS_STATUS_TEXT_IP_ADDRESS {
            get {
                return ResourceManager.GetString("PS_STATUS_TEXT_IP_ADDRESS", resourceCulture);
            }
        }
        
        internal static string PS_STATUS_TEXT_SUBNET_MASK {
            get {
                return ResourceManager.GetString("PS_STATUS_TEXT_SUBNET_MASK", resourceCulture);
            }
        }
        
        internal static string LOG_GUI_INITIALIZED {
            get {
                return ResourceManager.GetString("LOG_GUI_INITIALIZED", resourceCulture);
            }
        }
        
        internal static string PS_HELP_AT {
            get {
                return ResourceManager.GetString("PS_HELP_AT", resourceCulture);
            }
        }
        
        internal static string PS_HELP_INTRO {
            get {
                return ResourceManager.GetString("PS_HELP_INTRO", resourceCulture);
            }
        }
        
        internal static string PS_HELP_PS {
            get {
                return ResourceManager.GetString("PS_HELP_PS", resourceCulture);
            }
        }
        
        internal static string PS_HELP_PROXY {
            get {
                return ResourceManager.GetString("PS_HELP_PROXY", resourceCulture);
            }
        }
        
        internal static string PS_HELP_CERT_ANDROID {
            get {
                return ResourceManager.GetString("PS_HELP_CERT_ANDROID", resourceCulture);
            }
        }
        
        internal static string PS_HELP_CERT_IOS {
            get {
                return ResourceManager.GetString("PS_HELP_CERT_IOS", resourceCulture);
            }
        }
        
        internal static string PS_HELP_BACK_BUTTON {
            get {
                return ResourceManager.GetString("PS_HELP_BACK_BUTTON", resourceCulture);
            }
        }
        
        internal static string LAN_CODE {
            get {
                return ResourceManager.GetString("LAN_CODE", resourceCulture);
            }
        }
        
        internal static string SETTINGS_CATEGORY_GENERAL {
            get {
                return ResourceManager.GetString("SETTINGS_CATEGORY_GENERAL", resourceCulture);
            }
        }
        
        internal static string SETTINGS_CATEGORY_IN_GAME {
            get {
                return ResourceManager.GetString("SETTINGS_CATEGORY_IN_GAME", resourceCulture);
            }
        }
        
        internal static string SETTINGS_IN_GAME_LANGUAGE {
            get {
                return ResourceManager.GetString("SETTINGS_IN_GAME_LANGUAGE", resourceCulture);
            }
        }
        
        internal static string SETTINGS_GENERAL_LANGUAGE {
            get {
                return ResourceManager.GetString("SETTINGS_GENERAL_LANGUAGE", resourceCulture);
            }
        }
        
        internal static string LAN_DEFAULT {
            get {
                return ResourceManager.GetString("LAN_DEFAULT", resourceCulture);
            }
        }
        
        internal static string SETTINGS_INFO_REQUIRE_RESTART {
            get {
                return ResourceManager.GetString("SETTINGS_INFO_REQUIRE_RESTART", resourceCulture);
            }
        }
        
        internal static string SETTINGS_INFO_TRANSLATION_PROVIDER {
            get {
                return ResourceManager.GetString("SETTINGS_INFO_TRANSLATION_PROVIDER", resourceCulture);
            }
        }
        
        internal static string PROJ_DESC_EUCALYPTUS {
            get {
                return ResourceManager.GetString("PROJ_DESC_EUCALYPTUS", resourceCulture);
            }
        }
        
        internal static string SETTINGS_CATEGORY_SECURITY {
            get {
                return ResourceManager.GetString("SETTINGS_CATEGORY_SECURITY", resourceCulture);
            }
        }
        
        internal static string SETTINGS_SECURITY_REISSUE_CERT {
            get {
                return ResourceManager.GetString("SETTINGS_SECURITY_REISSUE_CERT", resourceCulture);
            }
        }
        
        internal static string SETTINGS_SECURITY_REISSUE_BUTTON {
            get {
                return ResourceManager.GetString("SETTINGS_SECURITY_REISSUE_BUTTON", resourceCulture);
            }
        }
        
        internal static string SETTINGS_INFO_REISSUE_CERT {
            get {
                return ResourceManager.GetString("SETTINGS_INFO_REISSUE_CERT", resourceCulture);
            }
        }
        
        internal static string SETTINGS_GENERAL_CHECK_UPDATE {
            get {
                return ResourceManager.GetString("SETTINGS_GENERAL_CHECK_UPDATE", resourceCulture);
            }
        }
        
        internal static string SETTINGS_GENERAL_CHECK_UPDATE_BUTTON {
            get {
                return ResourceManager.GetString("SETTINGS_GENERAL_CHECK_UPDATE_BUTTON", resourceCulture);
            }
        }
        
        internal static string SETTINGS_GENERAL_CHECK_UPDATE_TEXT_CHECKING {
            get {
                return ResourceManager.GetString("SETTINGS_GENERAL_CHECK_UPDATE_TEXT_CHECKING", resourceCulture);
            }
        }
        
        internal static string SETTINGS_GENERAL_CHECK_UPDATE_TEXT_FOUND {
            get {
                return ResourceManager.GetString("SETTINGS_GENERAL_CHECK_UPDATE_TEXT_FOUND", resourceCulture);
            }
        }
        
        internal static string SETTINGS_GENERAL_CHECK_UPDATE_TEXT_NOT_FOUND {
            get {
                return ResourceManager.GetString("SETTINGS_GENERAL_CHECK_UPDATE_TEXT_NOT_FOUND", resourceCulture);
            }
        }
        
        internal static string SETTINGS_GENERAL_UPDATE_NOW_BUTTON {
            get {
                return ResourceManager.GetString("SETTINGS_GENERAL_UPDATE_NOW_BUTTON", resourceCulture);
            }
        }
        
        internal static string SETTINGS_GENERAL_UPDATE_CHANNEL {
            get {
                return ResourceManager.GetString("SETTINGS_GENERAL_UPDATE_CHANNEL", resourceCulture);
            }
        }
        
        internal static string SETTINGS_GENERAL_AUTO_UPDATE {
            get {
                return ResourceManager.GetString("SETTINGS_GENERAL_AUTO_UPDATE", resourceCulture);
            }
        }
        
        internal static string SETTINGS_SECURITY_ONLINE_DECRYPTION {
            get {
                return ResourceManager.GetString("SETTINGS_SECURITY_ONLINE_DECRYPTION", resourceCulture);
            }
        }
        
        internal static string SETTINGS_DIALOG_SAVE_TITLE {
            get {
                return ResourceManager.GetString("SETTINGS_DIALOG_SAVE_TITLE", resourceCulture);
            }
        }
        
        internal static string SETTINGS_DIALOG_SAVE_FILE_TYPE {
            get {
                return ResourceManager.GetString("SETTINGS_DIALOG_SAVE_FILE_TYPE", resourceCulture);
            }
        }
        
        internal static string LOG_UPDATE_DOWNLOADED {
            get {
                return ResourceManager.GetString("LOG_UPDATE_DOWNLOADED", resourceCulture);
            }
        }
        
        internal static string LOG_UPDATE_FOUND {
            get {
                return ResourceManager.GetString("LOG_UPDATE_FOUND", resourceCulture);
            }
        }
        
        internal static string LOG_UPDATE_CHECKING {
            get {
                return ResourceManager.GetString("LOG_UPDATE_CHECKING", resourceCulture);
            }
        }
        
        internal static string LOG_UPDATE_NOT_FOUND {
            get {
                return ResourceManager.GetString("LOG_UPDATE_NOT_FOUND", resourceCulture);
            }
        }
        
        internal static string LOG_AT_GOT_UUID {
            get {
                return ResourceManager.GetString("LOG_AT_GOT_UUID", resourceCulture);
            }
        }
        
        internal static string LOG_AT_GOT_CODE {
            get {
                return ResourceManager.GetString("LOG_AT_GOT_CODE", resourceCulture);
            }
        }
        
        internal static string LOG_AT_GOT_ACCESSORIES {
            get {
                return ResourceManager.GetString("LOG_AT_GOT_ACCESSORIES", resourceCulture);
            }
        }
        
        internal static string LOG_AT_GOT_CARDS {
            get {
                return ResourceManager.GetString("LOG_AT_GOT_CARDS", resourceCulture);
            }
        }
        
        internal static string LOG_AT_GOT_DECKS {
            get {
                return ResourceManager.GetString("LOG_AT_GOT_DECKS", resourceCulture);
            }
        }
        
        internal static string LOG_AT_GOT_ITEMS {
            get {
                return ResourceManager.GetString("LOG_AT_GOT_ITEMS", resourceCulture);
            }
        }
        
        internal static string LOG_AT_GET_TITLES {
            get {
                return ResourceManager.GetString("LOG_AT_GET_TITLES", resourceCulture);
            }
        }
        
        internal static string LOG_AT_GOT_CHARACTER_FAMILIARITIES {
            get {
                return ResourceManager.GetString("LOG_AT_GOT_CHARACTER_FAMILIARITIES", resourceCulture);
            }
        }
        
        internal static string LOG_AT_GOT_HEADER {
            get {
                return ResourceManager.GetString("LOG_AT_GOT_HEADER", resourceCulture);
            }
        }
        
        internal static string LOG_AT_GOT_USER_INFO {
            get {
                return ResourceManager.GetString("LOG_AT_GOT_USER_INFO", resourceCulture);
            }
        }
        
        internal static string LOG_VERSION {
            get {
                return ResourceManager.GetString("LOG_VERSION", resourceCulture);
            }
        }
        
        internal static string LOG_LISTENING_AT {
            get {
                return ResourceManager.GetString("LOG_LISTENING_AT", resourceCulture);
            }
        }
        
        internal static string LOG_AT_FINISH_EXIT {
            get {
                return ResourceManager.GetString("LOG_AT_FINISH_EXIT", resourceCulture);
            }
        }
        
        internal static string LOG_PS_ENTER_TO_EXIT {
            get {
                return ResourceManager.GetString("LOG_PS_ENTER_TO_EXIT", resourceCulture);
            }
        }
        
        internal static string LOG_PS_REGISTER_NEW_PLAYER {
            get {
                return ResourceManager.GetString("LOG_PS_REGISTER_NEW_PLAYER", resourceCulture);
            }
        }
        
        internal static string LOG_PS_CREATE_SESSION {
            get {
                return ResourceManager.GetString("LOG_PS_CREATE_SESSION", resourceCulture);
            }
        }
        
        internal static string LOG_LIBGK_LAMBDA_FAILED {
            get {
                return ResourceManager.GetString("LOG_LIBGK_LAMBDA_FAILED", resourceCulture);
            }
        }
        
        internal static string LOG_PS_ACCOUNT_BANNING {
            get {
                return ResourceManager.GetString("LOG_PS_ACCOUNT_BANNING", resourceCulture);
            }
        }
        
        internal static string LOG_PS_ACCOUNT_BANNED {
            get {
                return ResourceManager.GetString("LOG_PS_ACCOUNT_BANNED", resourceCulture);
            }
        }
        
        internal static string LOG_PS_ACCESSORY_ASSIGN_NEW {
            get {
                return ResourceManager.GetString("LOG_PS_ACCESSORY_ASSIGN_NEW", resourceCulture);
            }
        }
        
        internal static string LOG_PS_CARD_ASSIGN_NEW {
            get {
                return ResourceManager.GetString("LOG_PS_CARD_ASSIGN_NEW", resourceCulture);
            }
        }
        
        internal static string LOG_PS_FRIEND_REQUEST_FOUND {
            get {
                return ResourceManager.GetString("LOG_PS_FRIEND_REQUEST_FOUND", resourceCulture);
            }
        }
        
        internal static string LOG_PS_FRIEND_REQUEST_CREATED {
            get {
                return ResourceManager.GetString("LOG_PS_FRIEND_REQUEST_CREATED", resourceCulture);
            }
        }
        
        internal static string LOG_PS_FRIEND_REQUEST_SENT {
            get {
                return ResourceManager.GetString("LOG_PS_FRIEND_REQUEST_SENT", resourceCulture);
            }
        }
        
        internal static string LOG_PS_FRIEND_REQUEST_REMOVED {
            get {
                return ResourceManager.GetString("LOG_PS_FRIEND_REQUEST_REMOVED", resourceCulture);
            }
        }
        
        internal static string LOG_PS_FRIEND_REQUEST_DELETED {
            get {
                return ResourceManager.GetString("LOG_PS_FRIEND_REQUEST_DELETED", resourceCulture);
            }
        }
        
        internal static string LOG_PS_FRIEND_REQUEST_UNKNOWN {
            get {
                return ResourceManager.GetString("LOG_PS_FRIEND_REQUEST_UNKNOWN", resourceCulture);
            }
        }
        
        internal static string LOG_PS_FRIEND_REQUEST_ACCEPTED {
            get {
                return ResourceManager.GetString("LOG_PS_FRIEND_REQUEST_ACCEPTED", resourceCulture);
            }
        }
        
        internal static string LOG_PS_FRIEND_REQUEST_REJECTED {
            get {
                return ResourceManager.GetString("LOG_PS_FRIEND_REQUEST_REJECTED", resourceCulture);
            }
        }
        
        internal static string LOG_PS_LOCAL_DATA_UPDATING {
            get {
                return ResourceManager.GetString("LOG_PS_LOCAL_DATA_UPDATING", resourceCulture);
            }
        }
        
        internal static string LOG_PS_LOCAL_DATA_DOWNLOADING {
            get {
                return ResourceManager.GetString("LOG_PS_LOCAL_DATA_DOWNLOADING", resourceCulture);
            }
        }
        
        internal static string LOG_PS_LOCAL_DATA_UP_TO_DATE {
            get {
                return ResourceManager.GetString("LOG_PS_LOCAL_DATA_UP_TO_DATE", resourceCulture);
            }
        }
        
        internal static string LOG_PS_LOCAL_DATA_UPDATED {
            get {
                return ResourceManager.GetString("LOG_PS_LOCAL_DATA_UPDATED", resourceCulture);
            }
        }
        
        internal static string LOG_PS_REDIRECT_API {
            get {
                return ResourceManager.GetString("LOG_PS_REDIRECT_API", resourceCulture);
            }
        }
        
        internal static string LOG_PS_SCENARIO_LANGUAGE {
            get {
                return ResourceManager.GetString("LOG_PS_SCENARIO_LANGUAGE", resourceCulture);
            }
        }
        
        internal static string LOG_PS_GOT_CONNECTION {
            get {
                return ResourceManager.GetString("LOG_PS_GOT_CONNECTION", resourceCulture);
            }
        }
        
        internal static string LOG_PS_API_NOT_IMPLEMENTED {
            get {
                return ResourceManager.GetString("LOG_PS_API_NOT_IMPLEMENTED", resourceCulture);
            }
        }
        
        internal static string LOG_PS_API_ERROR_TEMPLATE {
            get {
                return ResourceManager.GetString("LOG_PS_API_ERROR_TEMPLATE", resourceCulture);
            }
        }
        
        internal static string LOG_PS_ACCESSORY_ENHANCEMENT_LEVEL {
            get {
                return ResourceManager.GetString("LOG_PS_ACCESSORY_ENHANCEMENT_LEVEL", resourceCulture);
            }
        }
        
        internal static string LOG_PS_ACCESSORY_QUANTITY_DECREASED {
            get {
                return ResourceManager.GetString("LOG_PS_ACCESSORY_QUANTITY_DECREASED", resourceCulture);
            }
        }
        
        internal static string LOG_PS_BRAVE_COIN_INCREASE {
            get {
                return ResourceManager.GetString("LOG_PS_BRAVE_COIN_INCREASE", resourceCulture);
            }
        }
        
        internal static string LOG_PS_MONEY_DECREASED {
            get {
                return ResourceManager.GetString("LOG_PS_MONEY_DECREASED", resourceCulture);
            }
        }
        
        internal static string LOG_PS_ACCESSORY_ASSIGN_DEFAULT {
            get {
                return ResourceManager.GetString("LOG_PS_ACCESSORY_ASSIGN_DEFAULT", resourceCulture);
            }
        }
        
        internal static string LOG_PS_CARD_ASSIGN_DEFAULT {
            get {
                return ResourceManager.GetString("LOG_PS_CARD_ASSIGN_DEFAULT", resourceCulture);
            }
        }
        
        internal static string LOG_PS_DECK_SET_DEFAULT {
            get {
                return ResourceManager.GetString("LOG_PS_DECK_SET_DEFAULT", resourceCulture);
            }
        }
        
        internal static string LOG_PS_CARD_ENHANCMENT_COOKING_CHARACTER {
            get {
                return ResourceManager.GetString("LOG_PS_CARD_ENHANCMENT_COOKING_CHARACTER", resourceCulture);
            }
        }
        
        internal static string LOG_PS_CARD_ENHANCEMENT_BIG_HIT {
            get {
                return ResourceManager.GetString("LOG_PS_CARD_ENHANCEMENT_BIG_HIT", resourceCulture);
            }
        }
        
        internal static string LOG_PS_CARD_ENHANCEMENT_ACTIVE_SKILL_LEVEL_UP_PROBABILITY {
            get {
                return ResourceManager.GetString("LOG_PS_CARD_ENHANCEMENT_ACTIVE_SKILL_LEVEL_UP_PROBABILITY", resourceCulture);
            }
        }
        
        internal static string LOG_PS_CARD_ENHANCEMENT_ACTIVE_SKILL_LEVEL_UP {
            get {
                return ResourceManager.GetString("LOG_PS_CARD_ENHANCEMENT_ACTIVE_SKILL_LEVEL_UP", resourceCulture);
            }
        }
        
        internal static string LOG_PS_CARD_ENHANCEMENT_SUPPORT_SKILL_LEVEL_UP_PROBABILITY {
            get {
                return ResourceManager.GetString("LOG_PS_CARD_ENHANCEMENT_SUPPORT_SKILL_LEVEL_UP_PROBABILITY", resourceCulture);
            }
        }
        
        internal static string LOG_PS_CARD_ENHANCEMENT_SUPPORT_SKILL_LEVEL_UP {
            get {
                return ResourceManager.GetString("LOG_PS_CARD_ENHANCEMENT_SUPPORT_SKILL_LEVEL_UP", resourceCulture);
            }
        }
        
        internal static string LOG_PS_CARD_ENHANCEMENT_AFFINITY_INCREASE {
            get {
                return ResourceManager.GetString("LOG_PS_CARD_ENHANCEMENT_AFFINITY_INCREASE", resourceCulture);
            }
        }
        
        internal static string LOG_PS_CARD_ENHANCEMENT_AFFINITY_ASSIST_LEVEL_INCREASE {
            get {
                return ResourceManager.GetString("LOG_PS_CARD_ENHANCEMENT_AFFINITY_ASSIST_LEVEL_INCREASE", resourceCulture);
            }
        }
        
        internal static string LOG_PS_ACCESSORY_QUANTITY_INCREASED {
            get {
                return ResourceManager.GetString("LOG_PS_ACCESSORY_QUANTITY_INCREASED", resourceCulture);
            }
        }
        
        internal static string LOG_PS_CARD_EVOLUTION_MASTER_ID_CHANGE {
            get {
                return ResourceManager.GetString("LOG_PS_CARD_EVOLUTION_MASTER_ID_CHANGE", resourceCulture);
            }
        }
        
        internal static string LOG_PS_CARD_EVOLUTION_LEVEL_CHANGE {
            get {
                return ResourceManager.GetString("LOG_PS_CARD_EVOLUTION_LEVEL_CHANGE", resourceCulture);
            }
        }
        
        internal static string LOG_PS_ITEM_QUANTITY_DECREASED {
            get {
                return ResourceManager.GetString("LOG_PS_ITEM_QUANTITY_DECREASED", resourceCulture);
            }
        }
        
        internal static string LOG_PS_FRIEND_DELETED {
            get {
                return ResourceManager.GetString("LOG_PS_FRIEND_DELETED", resourceCulture);
            }
        }
        
        internal static string LOG_PS_FRIEND_REQUEST_FOUND_SYMMETRIC {
            get {
                return ResourceManager.GetString("LOG_PS_FRIEND_REQUEST_FOUND_SYMMETRIC", resourceCulture);
            }
        }
        
        internal static string LOG_PS_PROFILE_UPDATED {
            get {
                return ResourceManager.GetString("LOG_PS_PROFILE_UPDATED", resourceCulture);
            }
        }
        
        internal static string PS_LOG_REGULATION_AGREED {
            get {
                return ResourceManager.GetString("PS_LOG_REGULATION_AGREED", resourceCulture);
            }
        }
        
        internal static string SETTINGS_INFO_COMING_SOON {
            get {
                return ResourceManager.GetString("SETTINGS_INFO_COMING_SOON", resourceCulture);
            }
        }
    }
}
