name: Build & Deploy Project

on:
  push:
    branches: [ "master", "release" ]

jobs:
  build_win:
    strategy:
      matrix:
        tfm: [ "net6.0" ]

    uses: ./.github/workflows/build.yml
    with:
      rid: win10-x64
      tfm: ${{ matrix.tfm }}
      build_host: windows-latest
    secrets: inherit

  build_linux:
    strategy:
      matrix:
        tfm: [ "net6.0" ]

    uses: ./.github/workflows/build.yml
    with:
      rid: linux-x64
      tfm: ${{ matrix.tfm }}
      build_host: ubuntu-latest
    secrets: inherit

  build_mac:
    strategy:
      matrix:
        rid: [ "osx-x64", "osx-arm64" ]
        tfm: [ "net6.0" ]

    uses: ./.github/workflows/build.yml
    with:
      rid: ${{ matrix.rid }}
      tfm: ${{ matrix.tfm }}
      build_host: macos-latest
    secrets: inherit

    
  
  upload:
  
    name: Upload ${{ matrix.rid }}, ${{ matrix.tfm }} to AWS
    needs: [build_win, build_linux, build_mac]
    
    strategy:
      matrix:
        rid: [ "win10-x64", "osx-x64", "osx-arm64", "linux-x64" ]
        tfm: [ "net6.0" ]
        
    runs-on: ubuntu-latest
    
    steps:
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1
    - name: Download Artifacts
      uses: actions/download-artifact@v3
      with:
        name: ${{ matrix.tfm }}-${{ matrix.rid }}
    - name: Archive Artifact
      run: zip ${{ matrix.tfm }}-${{ matrix.rid }}.zip ./* -r
    - name: Upload to AWS S3
      run: aws s3 cp ${{ matrix.tfm }}-${{ matrix.rid }}.zip s3://y3ps-publish/${{ github.ref_name }}/${{ github.run_number }}/${{ matrix.tfm }}-${{ matrix.rid }}.zip


  deploy:

    name: Update Latest Version Manifest on AWS
    needs: upload

    runs-on: ubuntu-latest

    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: Get Current Time
        run: echo "current_time=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Download Manifest File
        run: aws s3 cp s3://y3ps-publish/version.json version.json

      - name: Update "created_at"
        uses: jossef/action-set-json-field@v1
        with:
          file: version.json
          field: version_info.${{ github.ref_name }}.created_at
          value: ${{ env.current_time }}

      - name: Update "commit_sha"
        uses: jossef/action-set-json-field@v1
        with:
          file: version.json
          field: version_info.${{ github.ref_name }}.commit_sha
          value: ${{ github.sha }}

      - name: Update "ci_run"
        uses: jossef/action-set-json-field@v1
        with:
          file: version.json
          field: version_info.${{ github.ref_name }}.ci_run
          value: ${{ github.run_number }}

      - name: Upload Manifest File
        run: aws s3 cp version.json s3://y3ps-publish/version.json

      - name: Create "timestamp.json"
        run: echo "{}" > timestamp.json

      - name: Update "timestamp.json"
        uses: jossef/action-set-json-field@v1
        with:
          file: timestamp.json
          field: created_at
          value: ${{ env.current_time }}

      - name: Upload Timestamp File
        run: aws s3 cp timestamp.json s3://y3ps-publish/${{ github.ref_name }}/${{ github.run_number }}/timestamp.json

