name: Build & Deploy Project

on:
  push:
    branches: [ "master", "release", "app-bundle" ]

jobs:
  get_time:
        
    runs-on: ubuntu-latest

    name: Get Current Time
    steps:
      - name: Get Current Time
        run: echo "current_time=$(date +'%Y%m%d%H%M%S')" > build_time.txt
      - uses: actions/upload-artifact@v3
        with:
          name: build_time
          path: build_time.txt
          retention-days: 1


  build_win:
    needs: [get_time]
    strategy:
      matrix:
        tfm: [ "net6.0" ]

    uses: ./.github/workflows/build.yml
    with:
      rid: win10-x64
      tfm: ${{ matrix.tfm }}
      build_host: windows-latest
      use_tar: false
    secrets: inherit

  build_linux:
    needs: [get_time]
    strategy:
      matrix:
        tfm: [ "net6.0" ]

    uses: ./.github/workflows/build.yml
    with:
      rid: linux-x64
      tfm: ${{ matrix.tfm }}
      build_host: ubuntu-latest
      use_tar: true
    secrets: inherit

  build_mac:
    needs: [get_time]
    strategy:
      matrix:
        rid: [ "osx-x64", "osx-arm64" ]
        tfm: [ "net6.0" ]

    uses: ./.github/workflows/build.yml
    with:
      rid: ${{ matrix.rid }}
      tfm: ${{ matrix.tfm }}
      build_host: macos-latest
      publish_subfolder: '/Jinchoge.app/Contents/MacOS'
      publish_singlefile: 'false'
      use_tar: true
      bundle_mac: true
    secrets: inherit

    
  
  upload:
  
    name: Upload ${{ matrix.rid }}, ${{ matrix.tfm }} to AWS
    needs: [build_win, build_linux, build_mac]
    
    strategy:
      matrix:
        rid: [ "win10-x64", "osx-x64", "osx-arm64", "linux-x64" ]
        tfm: [ "net6.0" ]
        
    runs-on: ubuntu-latest
    
    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ matrix.rid }}
      - name: Upload to AWS S3
        run: aws s3 cp ${{ matrix.rid }}.* s3://y3ps-publish/${{ github.ref_name }}/${{ github.run_number }}/


  deploy:

    name: Update Latest Version Manifest on AWS
    needs: upload

    runs-on: ubuntu-latest

    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: Download Current Time
        uses: actions/download-artifact@v3
        with:
          name: build_time
      - name: Get Current Time
        run: cat build_time.txt >> $GITHUB_ENV

      - name: Download Manifest File
        run: aws s3 cp s3://y3ps-publish/version.json version.json

      - name: Update "created_at"
        uses: jossef/action-set-json-field@v1
        with:
          file: version.json
          field: version_info.${{ github.ref_name }}.created_at
          value: ${{ env.current_time }}

      - name: Update "commit_sha"
        uses: jossef/action-set-json-field@v1
        with:
          file: version.json
          field: version_info.${{ github.ref_name }}.commit_sha
          value: ${{ github.sha }}

      - name: Update "ci_run"
        uses: jossef/action-set-json-field@v1
        with:
          file: version.json
          field: version_info.${{ github.ref_name }}.ci_run
          value: ${{ github.run_number }}

      - name: Update "branch"
        uses: jossef/action-set-json-field@v1
        with:
          file: version.json
          field: version_info.${{ github.ref_name }}.branch
          value: ${{ github.ref_name }}




      - name: Update Artifacts (win10-x64)
        uses: jossef/action-set-json-field@v1
        with:
          file: version.json
          field: version_info.${{ github.ref_name }}.artifacts.win10-x64
          value: win10-x64.zip

      - name: Update Artifacts (osx-x64)
        uses: jossef/action-set-json-field@v1
        with:
          file: version.json
          field: version_info.${{ github.ref_name }}.artifacts.osx-x64
          value: osx-x64.tgz

      - name: Update Artifacts (osx-arm64)
        uses: jossef/action-set-json-field@v1
        with:
          file: version.json
          field: version_info.${{ github.ref_name }}.artifacts.osx-arm64
          value: osx-arm64.tgz

      - name: Update Artifacts (linux-x64)
        uses: jossef/action-set-json-field@v1
        with:
          file: version.json
          field: version_info.${{ github.ref_name }}.artifacts.linux-x64
          value: linux-x64.tgz




      - name: Upload Manifest File
        run: aws s3 cp version.json s3://y3ps-publish/version.json

      - name: Create "timestamp.json"
        run: echo "{}" > timestamp.json

      - name: Update "timestamp.json"
        uses: jossef/action-set-json-field@v1
        with:
          file: timestamp.json
          field: created_at
          value: ${{ env.current_time }}

      - name: Upload Timestamp File
        run: aws s3 cp timestamp.json s3://y3ps-publish/${{ github.ref_name }}/${{ github.run_number }}/timestamp.json

