name: Build Private Server GUI

on:
  push:
    branches: [ "master", "release" ]

jobs:
  build_win:
    strategy:
      matrix:
        tfm: [ "net6.0" ]

    uses: ./.github/workflows/publish.yml
      width:
        rid: win10-x64
        tfm: ${{ matrix.tfm }}
        build_host: windows-latest

  build_linux:
    strategy:
      matrix:
        tfm: [ "net6.0" ]

    uses: ./.github/workflows/publish.yml
      width:
        rid: linux-x64
        tfm: ${{ matrix.tfm }}
        build_host: ubuntu-latest

  build_mac:
    strategy:
      matrix:
        rid: [ "osx-x64", "osx-arm64" ]
        tfm: [ "net6.0" ]

    uses: ./.github/workflows/publish.yml
      width:
        rid: ${{ matrix.rid }}
        tfm: ${{ matrix.tfm }}
        build_host: macos-latest

    
  
  deploy:
  
    name: Upload ${{ matrix.rid }}, ${{ matrix.tfm }} to AWS
    needs: [build_win, build_linux, build_mac]
    
    strategy:
      matrix:
        rid: [ "win10-x64", "osx-x64", "osx-arm64", "linux-x64" ]
        tfm: [ "net6.0" ]
        
    runs-on: ubuntu-latest
    
    steps:
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1
    - name: Download Artifacts
      uses: actions/download-artifact@v3
      with:
        name: ${{ matrix.tfm }}-${{ matrix.rid }}
    - name: Archive Artifact
      run: zip ${{ matrix.tfm }}-${{ matrix.rid }}.zip ./* -r
    - name: Upload to AWS S3
      run: aws s3 cp ${{ matrix.tfm }}-${{ matrix.rid }}.zip s3://y3ps-publish/${{ github.run_number }}/${{ matrix.tfm }}-${{ matrix.rid }}.zip
